### ISSUE TITLE
max_seq_len Issue

### ISSUE THREAD

**Issue by zphang** [nyu-mll/jiant#1002]
There appears to be some issue with our tokenization/truncation that doesn't abide by the max_seq_len.

```
AssertionError: input length exceeds position embedding capacity, reduce max_seq_len
```

Here is a reproducible case:
```
python main.py --config jiant/config/superglue_bert.conf \
    --overrides "random_seed = 1234, cuda = 0, exp_name = \"testing\", run_name = qnli, batch_size = 2, input_module = albert-xxlarge-v2, pretrain_tasks = \"qnli\", target_tasks = \"\", do_pretrain = 1, do_target_task_training = 0, do_full_eval = 1, val_interval = 10000, max_seq_len=512, accumulation_steps=2"
```

**Comment by W4ngatang** [comment]
Yea, this is the issue I was discussing on Slack. The issue is that we
apply `max_seq_len` when loading the data, but since we might be
concatenating inputs later, we can easily be over `max_seq_len`. Right now
I'm hacking the relevant model interfaces so that when we concatenate, we
also apply some `max_seq_len`.

**Comment by pyeres** [comment]
Hey @W4ngatang, in your workaround where are you modifying `model_preprocessing_interface`? (`boundary_token_fn`?)

**Comment by W4ngatang** [comment]
In `apply_boundary_tokens`. I'll try and submit a WIP PR later today

**Comment by mahsash** [comment]
Hello.
I am using your library and I faced the same issue. Has it been solved now?

**Comment by pyeres** [comment]
> More precisely, I am using edge probing tasks. I added a new task but I get this error. Can you help me to solve it?

@mahsash, a fix that should cover your use case was merged into master today (61211f3).

**Comment by HaokunLiu** [comment]
When we do this, remember to add max_seq_len for egde probing tasks as well.

**Comment by naveenjafer** [comment]
Hi @pyeres @HaokunLiu  I seem to be facing this issue for edge probind task, could you please help me with this?

**Comment by naveenjafer** [comment]
The exact error that I receive is

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1002.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
