### ISSUE TITLE
Micro average logged as 0.000 for some tasks

### ISSUE THREAD

**Issue by pyeres** [nyu-mll/jiant#1011]
For a number of tasks the micro average is being logged as 0.000 during evaluation (other metrics look normal, e.g. loss and macro average), and in some cases the micro average behavior is different between single- and multi-GPU modes (zero for one, non-zero for the other):

- ccg (0.000 in multi- and single-GPU modes)
- wnli (0.000 in multi-GPU mode)
- winogender-diagnostic (0.000 in multi- and single-GPU modes)
- mrpc (0.000 in multi-GPU mode)
- qnli (0.000 in multi-GPU mode)
- sts-b (0.000 in multi-GPU mode)
- ...

**Comment by pruksmhc** [comment]
I've seen this error once before.This happened because a variable was a Tensor and not an int, and was rounded to 0.

**Comment by pyeres** [comment]
> I've seen this error once before.This happened because a variable was a Tensor and not an int, and was rounded to 0.

Thanks, @pruksmhc — confirmed this is an issue in Master. Patched w/ #1012. Can you review?

**Comment by pyeres** [comment]
Thanks for reviewing #1012, @pruksmhc — patch now in Master with https://github.com/nyu-mll/jiant/commit/19c8b3a172411bb59c3f54b6a72d858d604c252f.
