### ISSUE TITLE
EdgeProbing breaks after Multi-GPU

### ISSUE THREAD

**Issue by HaokunLiu** [nyu-mll/jiant#1017]
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    raise e  # re-raise exception, in case debugger is attached.
  File "main.py", line 16, in <module>
    main(sys.argv[1:])
  File "/home/hl3236/jiant/jiant/__main__.py", line 588, in main
    phase="pretrain",
  File "/home/hl3236/jiant/jiant/trainer.py", line 579, in train
    output_dict = self._forward(batch, task=task)
  File "/home/hl3236/jiant/jiant/trainer.py", line 1044, in _forward
    task.update_metrics(model_out, batch)
  File "/home/hl3236/jiant/jiant/tasks/tasks.py", line 288, in update_metrics
    raise NotImplementedError

**Comment by HaokunLiu** [comment]
@pruksmhc

**Comment by pruksmhc** [comment]
Haokun, we only stabilized multi-GPU for all non-edge probing tasks. For edge probing, you'll have to define a def update_metrics for each edge probing task where the function signature is update_metrics(out, batch). You can check out to see some examples: https://github.com/nyu-mll/jiant/blob/master/jiant/tasks/tasks.py

**Comment by HaokunLiu** [comment]
I am using single GPU.

**Comment by pruksmhc** [comment]
Ah - you'll unfortunately still have to update the update_metrics. We didn't do it for probing tasks in the fix PR. Sorry about that!

**Comment by HaokunLiu** [comment]
I don’t really understand how does edge probing work. You are experienced
in both edge probing and multi-GPU, I can’t think of any one better for
this job.

**Comment by pruksmhc** [comment]
Alright i'll take a look tomorrow

**Comment by pruksmhc** [comment]
Alright, I'll take a look at it tomorrow.

**Comment by HaokunLiu** [comment]
Thanks a lot!

**Comment by pyeres** [comment]
> Traceback (most recent call last):
> File "main.py", line 27, in
> raise e # re-raise exception, in case debugger is attached.
> File "main.py", line 16, in
> main(sys.argv[1:])
> File "/home/hl3236/jiant/jiant/**main**.py", line 588, in main
> phase="pretrain",
> File "/home/hl3236/jiant/jiant/trainer.py", line 579, in train
> output_dict = self._forward(batch, task=task)
> File "/home/hl3236/jiant/jiant/trainer.py", line 1044, in _forward
> task.update_metrics(model_out, batch)
> File "/home/hl3236/jiant/jiant/tasks/tasks.py", line 288, in update_metrics
> raise NotImplementedError

@HaokunLiu — can you please provide an example of a command you ran that triggered this error?
