### ISSUE TITLE
About nested configs

### ISSUE THREAD

**Issue by HaokunLiu** [nyu-mll/jiant#1022]
__Note: this issue need to be fixed before the taskmaster probing experiment__

We have many nested configs in default configs. Sometime we override them in specific experiment experiment. But it doesn't work as what people imagine.

For example, when there is
s2s {
    d_hid_dec = 100 
    n_layers_dec = 1 
    attention = "Bahdanau" 
    output_proj_input_dim = 100 
    beam_size = 10 
} 

in default, overriding with

s2s = {
    attention = none
} 

will only changes that specific term,yielding
s2s {
    d_hid_dec = 100
    n_layers_dec = 1
    attention = none
    output_proj_input_dim = 100
    beam_size = 10
}

This is also the case for edges-tmpl. 
edges-tmpl {
    span_classifier_loss_fn = "sigmoid"  // 'sigmoid' or 'softmax'
    classifier_span_pooling = "attn"  // 'attn' or 'x,y'
    classifier_hid_dim = 256
    classifier_dropout = 0.3
    pair_attn = 0
    max_vals = 100
    val_interval = 500
}

What's even worse, this template is copied by all edge probing tasks to be their specific config.
Since, in target training, task specific config has higher priority than general configs. We can not change the max_vals and val_interval of edge probing tasks by

max_vals = 10000
val_interval = 5000

like we usually do with other tasks. And due to how nested config is handed, there is no way we can remove max_vals and val_interval inside the brackets. 

One walkaround is to import from a clean version of the default, that does not have nested configs, created only for your specific project. But this cause error when comparing the config with the default config. Because we didn't consider the case of not using default config as the root when writing parse_json_diff in jiant/utils/utils.py.
```
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    main(sys.argv[1:])
  File "/home/hl3236/jiant/jiant/__main__.py", line 545, in main
    args, seed = initial_setup(args, cl_args)
  File "/home/hl3236/jiant/jiant/__main__.py", line 402, in initial_setup
    print_args = select_relevant_print_args(args)
  File "/home/hl3236/jiant/jiant/utils/utils.py", line 293, in select_relevant_print_args
    diff_args = Params.clone(diff_args)
  File "/home/hl3236/jiant/jiant/utils/config.py", line 41, in clone
    raise ValueError("Cannot clone from type: " + str(type(source)))
ValueError: Cannot clone from type: <class 'NoneType'>
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    raise e  # re-raise exception, in case debugger is attached.
  File "main.py", line 16, in <module>
    main(sys.argv[1:])
  File "/home/hl3236/jiant/jiant/__main__.py", line 545, in main
    args, seed = initial_setup(args, cl_args)
  File "/home/hl3236/jiant/jiant/__main__.py", line 402, in initial_setup
    print_args = select_relevant_print_args(args)
  File "/home/hl3236/jiant/jiant/utils/utils.py", line 293, in select_relevant_print_args
    diff_args = Params.clone(diff_args)
  File "/home/hl3236/jiant/jiant/utils/config.py", line 41, in clone
    raise ValueError("Cannot clone from type: " + str(type(source)))
ValueError: Cannot clone from type: <class 'NoneType'>
```

**Comment by pyeres** [comment]
> **Note: this issue need to be fixed before the taskmaster probing experiment**
> 
> We have many nested configs in default configs. Sometime we override them in specific experiment experiment. But it doesn't work as what people imagine.
> 
> For example, when there is
> s2s {
> d_hid_dec = 100
> n_layers_dec = 1
> attention = "Bahdanau"
> output_proj_input_dim = 100
> beam_size = 10
> }
> 
> in default, overriding with
> 
> s2s = {
> attention = none
> }
> 
> will only changes that specific term,yielding
> s2s {
> d_hid_dec = 100
> n_layers_dec = 1
> attention = none
> output_proj_input_dim = 100
> beam_size = 10
> }

Thanks for calling this out, @HaokunLiu — for this case can you get the behavior you want by [setting the key of the field you want to override to `null`](https://github.com/lightbend/config/blob/master/HOCON.md#duplicate-keys-and-object-merging) before the override?

```
s2s = null
s2s = {
    attention = none
}
```

**Comment by iftenney** [comment]
Chiming in from the past here: the current config system was built in ~2 days, and it may be time for a proper overhaul :) May be worth revisiting #475 and porting configs to [jsonnet](https://jsonnet.org/)?

HOCON is pretty wonky with nested overrides, relying as it does on sequential evaluation rather than proper import / merge semantics.

**Comment by pyeres** [comment]
@HaokunLiu — planning to close this issue as resolved or stale. If you think there's still an issue (after applying the approach suggested [here](https://github.com/nyu-mll/jiant/issues/1022#issuecomment-593695851)), please respond here.

**Comment by HaokunLiu** [comment]
Yes, we can close this as solved. thanks.
