### ISSUE TITLE
Does it possible to load and evaluate models using jiant other than the models implemented here?

### ISSUE THREAD

**Issue by shanybarhom** [nyu-mll/jiant#1042]

**Comment by sleepinyourhat** [comment]
Could you say more? I'm not sure what kinds of model you have in mind.

**Comment by shanybarhom** [comment]
Hi, thanks for your response.
Let's say for example that I have implemented a new model with a novel pre-training method (that is not implemented in huggingface repo) and I would like to use jiant to fine-tune or evaluate it on GLUE/SuperGLUE, is this possible? For example, by adjusting my model to jiant's interface.

Thanks!

**Comment by sleepinyourhat** [comment]
That should be possible, but it's not something that's currently well documented/supported, so you'll have to be a bit brave. I see two options:

- If the model closely resembles one of the models in HuggingFace's Transformers, then add your model to a fork of Transformers, import that fork of Transformers, and then modify `jiant` to acces sit. (You should be able to look for all occurrences of `roberta` or `albert` to see what to modify.)
- If Transformers doesn't seem helpful for what you're doing, try to follow the code paths that implement our CBOW and BiLSTM baselines. These are somewhat complex, but you will find PyTorch modules that you could replace in your own fork of `jiant`.

**Comment by shanybarhom** [comment]
Thank you!
