### ISSUE TITLE
How to use the scripts in `/scripts`?

### ISSUE THREAD

**Issue by cjlovering** [nyu-mll/jiant#1050]
I can run jiant as outlined in the tutorial, but when I try to import jiant in an file from the scripts folder it breaks. A stray comment in one of the files suggested that there are (or should be) symlinks?

```
$ conda activate jiant; . ./user_config.sh; python main.py --config_file jiant/config/default.conf
% works!
```

```
% I am interested in running a custom (new) script, but for example:
$ conda activate jiant; ./user_config.sh; python scripts/ccg/align_tags_to_bert.py 
Traceback (most recent call last):
  File "scripts/ccg/align_tags_to_bert.py", line 8, in <module>
    from jiant.utils.retokenize import get_aligner_fn
ModuleNotFoundError: No module named 'jiant'
```

**Comment by pyeres** [comment]
Hi @cjlovering — does running your script [like this (using the `-m` option)](https://github.com/nyu-mll/jiant/blob/master/scripts/ccg/align_tags_to_bert.py#L12-L14) resolve your issue?

**Comment by cjlovering** [comment]
Thanks! This works!
