### ISSUE TITLE
Setup jiant for MultiRC

### ISSUE THREAD

**Issue by roongtarohit** [nyu-mll/jiant#1052]
Hi,

I want to setup jiant for my university project. I am building a model for MultiRC. As per the jiant paper, baseline model gives F1 and EM values are 70.5 and 24.7 respectively.
However, i am unable to get this result. I made few change in the superglue_bert.conf.

Can someone please help me out what would be the appropriate configuration for MultiRC?

Thanks!

**Comment by pruksmhc** [comment]
It seems as though in the most recent performance runs (after we made many changes), MultiRC results had somewhat decreased. 
https://github.com/nyu-mll/jiant/pull/992
I would try using the v1.0.0 release, which was released as the codebase for the  final version of the SuperGLUE leaderboard. 
https://github.com/nyu-mll/jiant/releases/tag/v1.0.0

**Comment by roongtarohit** [comment]
Hi Yada,

Thank you. I will try out the initial version. Is it possible know what changes were implemented? I can do analysis.

Thanks!

**Comment by roongtarohit** [comment]
Hi @pruksmhc ,

I am facing some errors while running v1.0.0 -

1) Since MosesTokenizer has been moved out of NLTK, I replaced ntlk with sacremoses in utils.py and tokenizers.py
2) After the above,
Traceback (most recent call last):
  File "main.py", line 588, in <module>
    raise e  # re-raise exception, in case debugger is attached.
  File "main.py", line 577, in <module>
    main(sys.argv[1:])
  File "main.py", line 469, in main
    pretrain_tasks, target_tasks, vocab, word_embs = build_tasks(args)
  File "/home/rroongta/jiant1.0/jiant/jiant/preprocess.py", line 290, in build_tasks
    indexers = build_indexers(args)
  File "/home/rroongta/jiant1.0/jiant/jiant/preprocess.py", line 261, in build_indexers
    "BERT models use custom WPM tokenization for "
AssertionError: BERT models use custom WPM tokenization for each model, so tokenizer must match the specified BERT model.

Should I use other version?

**Comment by roongtarohit** [comment]
Hi @pruksmhc ,

Thank you. I will try out the initial version. Is it possible to know what changes were implemented? I need to do analysis.

Thanks!

**Comment by roongtarohit** [comment]
Hi @pruksmhc ,

I am getting the below CUDA error when the model starts the target-training on multirc:

RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 11.17 GiB total capacity; 10.34 GiB already allocated; 9.75 MiB free; 540.65 MiB cached).
Could you please help?

**Comment by pruksmhc** [comment]
Hi, that means you have to run on a bigger GPU. We used P40s for our experiments.

**Comment by roongtarohit** [comment]
Hi @pruksmhc 

Thank you, will give a run.
Could you please let me know the right set of configuration for multiRC? 
At the moment, I am using superglue_bert.conf with target_tasks="multirc".

**Comment by W4ngatang** [comment]
Hi Rohit,

We used the `superglue_bert.conf` config file. You mentioned making a few changes, could you share the changes you made?

NB: similar issue to #1081

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1052.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
