### ISSUE TITLE
special approval to use the Cove data (that's in the salesforce project)

### ISSUE THREAD

**Issue by lovodkin93** [nyu-mll/jiant#1053]
i'm trying to run an edge_probing of the cove data, using the parameters in jiant/config/edgeprobe/edgeprobe_cove.conf.

But when i run it, i keep having the following error:
File "/cs/labs/oabend/lovodkin93/jiant_rep/jiant/jiant/models.py", line 377, in build_embeddings
    from jiant.modules.cove.cove import MTLSTM as cove_lstm
ModuleNotFoundError: No module named 'jiant.modules.cove.cove'

i've tried to seperate the import line into 2 import line in order to understand which of the modules is inrecognisable and got the following error:
from jiant.modules.cove import cove
ImportError: cannot import name 'cove'

it appears i cannot import anything from jiant.modules.cove, which is saw in the ".gitmodules" file is connected to https://github.com/salesforce/cove.git, so i would like to know if the reason i cannot import anything from there is because i need to get some sort of importing approval, and if so, how do i get it.
Thank you very much!

**Comment by sleepinyourhat** [comment]
Hrm, did you follow the full installation instructions? There's a step that explicitly loads those modules. 

(I've never heard of any permission system for imports...)

**Comment by lovodkin93** [comment]
i think so.
can you please refer to the specific part that loads those modules? maybe i've missed that
@sleepinyourhat

**Comment by sleepinyourhat** [comment]
The instructions in section 1 here (before `conda env create ...`) should do it: 

https://github.com/nyu-mll/jiant/blob/master/tutorials/setup_tutorial.md

**Comment by sleepinyourhat** [comment]
In any case, you want to make sure that there are actual local files on disk for you in the cove directory that you're trying to import from.

**Comment by lovodkin93** [comment]
> The instructions in section 1 here (before `conda env create ...`) should do it:
> 
> https://github.com/nyu-mll/jiant/blob/master/tutorials/setup_tutorial.md

that's exactly what i did:
i ran the "git clone --branch v1.3.1  --recursive https://github.com/nyu-mll/jiant.git jiant" command
and then the "conda env create..." one.
should i have run the other two command too? the "git checkout tags/v1.3.1 -b 1.3.1_master" and the "git submodule update --init --recursive"?

**Comment by lovodkin93** [comment]
> In any case, you want to make sure that there are actual local files on disk for you in the cove directory that you're trying to import from.

i checked, and by the looks of it, once i enter thr cove directory - i take me to the https://github.com/salesforce/cove project, which i am guessing means it's not local.
is there a way to make it local now? without redoing git clone to the jiant project and redoing the whole pre-process phase?

**Comment by sleepinyourhat** [comment]
I'm not sure—look at some documentation for submodules, or else clone a
second copy of jiant and try to move files around to get what you want?

**Comment by lovodkin93** [comment]
ok, i'll give it a go.
Thank you so much!

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/1053.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
