### ISSUE TITLE
finetuning bert model

### ISSUE THREAD

**Issue by lovodkin93** [nyu-mll/jiant#1063]
Hey everyone,
I want to do finetuning of Bert for the Coreference task.
I basically want to see the effect of the "deeper" layers of Bert on the Coreference task, and therefore I want to freeze the training of the lower layers and train just the deep ones.
So I basically have 2 questions:
1. should I use the "edgeprobe_bert.conf" file, located in the "config/edgeprobe" directory as a starting point, and just ad prameters to it? (and then use it similiarly to what was written in the README file located in the "probing" directory:
python main.py --config_file jiant/config/edgeprobe/edgeprobe_cove.conf \
  -o "target_tasks=edges-spr2,exp_name=ep_cove_demo" (and just replace the target task with "edges-coref-ontonotes")?
2. does anyone have an idea as to how to freeze certain layers in BERT? 
Thank you very much!
Aviv.

**Comment by iftenney** [comment]
1. Yes, that should run the correct model. As a reference, these are the configs from the paper: https://github.com/nyu-mll/jiant/blob/master/scripts/edgeprobing/exp_fns.sh#L179. If you want to finetune, you can probably adapt the params from `bert_mix_expt` by setting `transformers_output_mode=top` and `transfer_paradigm = "finetune"`.

2. I don't think there's support for this in the config system; you'd need to modify the model code and set those layers to be non-trainable.
