### ISSUE TITLE
Google Cloud Platform Authenctication

### ISSUE THREAD

**Issue by lovodkin93** [nyu-mll/jiant#1065]
hi,
So i've tried to run the experiment from the paper, as described in the README file located in the probing directory, by running the commands:
pushd ${PWD%/jiant*}/jiant
source scripts/edges/exp_fns.sh
bert_mix_exp edges-srl-ontonotes bert-base-uncased

but i keep getting the following error:
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started

From what I read online, it seems i need to get some key to allow me to work on the Google Cloud Platform, but when i try to obtain it, it asks me for the project's ID.
Does anyone know what the jiant project's ID in regard with this Google Cloud Platform key? Or has anyone encountered this problem before and knows how to solve it?
Thanks!

**Comment by lovodkin93** [comment]
so apparently the flag "--remote_log" was added to the command line generated by exp_fns.sh, and omitting this flag solved this problem. Does anyone know if this flag has any significance on the results? 
Thanks.
@iftenney @

**Comment by iftenney** [comment]
Whoops, sorry - this flag only works on Google Cloud Platform. It's safe to remove - all it does is stream logs to the Cloud Console.
