### ISSUE TITLE
Results with pretrain_data_fraction args

### ISSUE THREAD

**Issue by claravania** [nyu-mll/jiant#1066]
I'm trying to train MNLI in low-data regime (~750 examples) on RoBERTa, using the pretrain_data_fraction argument. I'm using default RoBERTa hyperparameter setup, but set the num epochs higher to allow the model trained longer. However, I got quite high performance 89.02 macro_avg, just slightly lower than using full data, 90.2 macro_avg. Could there possibly be some bugs?

Attaching log file, config file, and my command.

Command:
`python main.py --config_file jiant/config/nli-roberta_conf.txt -o "run_name=run1, random_seed=123456"`

[nli-roberta_conf.txt](https://github.com/nyu-mll/jiant/files/4477438/nli-roberta_conf.txt)
[log.log](https://github.com/nyu-mll/jiant/files/4477412/log.log)

(changed .conf to _conf.txt since I can't upload the format to GitHub)

**Comment by pyeres** [comment]
It looks like the task's `task.train_data`, which is an instance generator with a pretraining data fraction arg, is being overwritten with an instance generator with the _target_ data fraction arg when task name appears in both the `pretrain_task_names` and `target_task_names`:

https://github.com/nyu-mll/jiant/blob/de3c44a6c2aad2bdfc5bc3047e063fd03c6c4c12/jiant/preprocess.py#L421-L436

**Comment by pyeres** [comment]
Update: I'm working on a PR to address this.
