### ISSUE TITLE
Backronym "jiant"?

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#1067]
@zphang proposed "jiant is an nlp toolkit", and another viable variant could be "jiant is an nlu toolkit". Either way, it's helpful to keep it in lowercase. Should we make one of these official-ish?

What do people think? @W4ngatang @iftenney @pruksmhc @pyeres?

**Comment by iftenney** [comment]
I like both of these, slight bias to `nlp` over `nlu`.

**Comment by pyeres** [comment]
Official w/ PR https://github.com/nyu-mll/jiant/pull/1075, merged and released in v1.3.2.
