### ISSUE TITLE
getting the probed model

### ISSUE THREAD

**Issue by lovodkin93** [nyu-mll/jiant#1072]
Hey everyone,
i have this little project where i need to check some features of the probed BERT model.
So i followed the instructions of how to probe a model, but all I got were results of the training (F1, precision, etc).
Is there any way to also get the probed model?
Also, is there a way to not use some of the ontonotes data in the probing proccess, so i can use it in the extra training i need to do afterwards (as part of the feature checking)?
Thanks!

**Comment by sleepinyourhat** [comment]
Checking the features: I'm not quite sure what you mean. jiant doesn't expose hidden states or parameters anywhere explicitly, so you'll likely have to do some engineering on your own. If you work your way through the classifier code, you'll likely be able to add any print statement (or file-writes) you need in the forward function of the relevant classifier module, and then run an evaluation-only run with your modified code. Again, though, this is pretty far from anything we can guide you through in detail.

For skipping Ontonotes data, I'm also somewhat confused—AFAIK, there are no tasks in jiant that use Ontonotes _and_ other datasets.

**Comment by iftenney** [comment]
Also not sure I follow - what's the extra training?

If you're looking for the weights of the probing model, they should be saved as checkpoints in the run directory.

If you want to hold out some of the data, you can just make new versions of the data files. The format is JSONL, so you can use `head`, `tail`, `jq`, etc. to split by line.
