### ISSUE TITLE
Transient test failures from MLM/#1030

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#1076]
It looks like there's a probabilistic component to at least one of the tests introduced by #1030—it is failing and passing sporadically. As of now, CircleCI says that `jiant` is broken at head, since the recent README-only PR got unlucky and caused a random failure.

Please fix ASAP—by whatever means seem best in the context of the original PR—so that we can trust the results of the tests.

**Comment by pyeres** [comment]
Closing as addressed by @pruksmhc's changes w/ #1077 (now in master). Thanks @pruksmhc.
