### ISSUE TITLE
Support for external models query

### ISSUE THREAD

**Issue by dwlmt** [nyu-mll/jiant#1095]
Within jiant is are there support hooks for running an existing external model rather than defining everything in conf? The use case is I have a hierarchical model already created in allennlp and trained but want to be able to run the Glue and SuperGlue benchmark tasks. The model is based on a transformer but has more complex higher-level logic as well.

**Comment by sleepinyourhat** [comment]
Nope—sorry! This isn't something we support at the moment. It should be possible, if not super easy/documented, to trace down the code that we use to set up a BiLSTM model, and create a parallel code path for your Allen model.

FWIW, we'll likely further reduce support for `allennlp` and custom models in near-future versions, while making it easier to import new additions to Transformers.
