### ISSUE TITLE
WiC and winogender-diagnostic - TypeError: apply_standard_boundary_tokens() got an unexpected keyword argument 'get_offset'

### ISSUE THREAD

**Issue by hsajjad** [nyu-mll/jiant#1104]
Hi, 
I am getting the following error when training/finetuning on wic and winogender-diagnostic. The rest of the tasks are processed without a problem. Is there something that I am missing?

07/20 04:35:33 PM: 	Task wic (train): Indexing from scratch.
07/20 04:35:33 PM: Fatal error in main():
...
TypeError: apply_standard_boundary_tokens() got an unexpected keyword argument 'get_offset'

I am using the jiant/config/tutorial.conf

Thanks,
Hassan

**Comment by sleepinyourhat** [comment]
Hrm. @W4ngatang, @HaokunLiu, @zphang: Do you remember seeing this in any of our SuperGLUE runs?

**Comment by HaokunLiu** [comment]
I added the argument for transformer based input models,  but I forgot to
address the older models, these tasks probably only work for transformers
now.

If using an older model is necessary, adding a dummy argument to the
function mentioned the error message should fix the problem.

**Comment by hsajjad** [comment]
I am trying to reproduce the glove numbers reported in the paper so you are right that I am not using transformer based input models. I can try adding get_offset to the function apply_standard... if that's the right way to fix it
