### ISSUE TITLE
tutorial documentation

### ISSUE THREAD

**Issue by kwchurch** [nyu-mll/jiant#1106]
Installation from tutorial did not go smoothly

pip install pyhocon
pip install jsondiff
pip install python-Levenshtein

Then ran into error: pyhocon.exceptions.ConfigMissingException: 'No configuration setting found for key JIANT_PROJECT_PREFIX'

I was running:

   python main.py --config_file jiant/config/tutorial.conf --overrides "exp_name = my_exp, run_name = foobar"

Don't see anything in documentation that says anything about what needs to be in JIANT_PROJECT_PREFIX

**Comment by sleepinyourhat** [comment]
If I understand the issue correctly, you just need to set a couple of paths to point to working directories where you'd like checkpoints and logs to be stored. The instructions are in the same section as that run command, but appear right after it, which probably isn't the best design decision:

https://github.com/nyu-mll/jiant#running

If there's more to it than that, let me know. In any case, thanks for giving it a try. We're working on a cleaner/more usable rewrite (v2.0) that should be ready to go quite soon.

**Comment by kwchurch** [comment]
I have set up those variables.

The documentation doesn't say what needs to be in those variables.  I'm
just guessing.

Those instructions also don't mention a bunch of python packages that need
to be installed

After this first error, the script starts generating more recursive errors
while trying to catch the first error

echo ${JIANT_PROJECT_PREFIX}
> /mnt/big/kwc/jiant/proj
> (my_venv) kwc@bd-1:/mnt/big/kwc/useful_resources/jiant/jiant$ python
> main.py --config_file jiant/config/tutorial.conf --overrides "exp_name =
> my_exp, run_name = foobar"
> 08/03 07:43:02 AM: Better speed can be achieved with apex installed from
> https://www.github.com/nvidia/apex .
> 08/03 07:43:03 AM: Better speed can be achieved with apex installed from
> https://www.github.com/nvidia/apex .
> 08/03 07:43:03 AM: Better speed can be achieved with apex installed from
> https://www.github.com/nvidia/apex .
> 08/03 07:43:03 AM: instantiating registered subclass relu of <class
> 'allennlp.nn.activations.Activation'>
> 08/03 07:43:03 AM: instantiating registered subclass relu of <class
> 'allennlp.nn.activations.Activation'>
> 08/03 07:43:03 AM: instantiating registered subclass relu of <class
> 'allennlp.nn.activations.Activation'>
> 08/03 07:43:03 AM: instantiating registered subclass relu of <class
> 'allennlp.nn.activations.Activation'>
> 08/03 07:43:04 AM: PyTorch version 1.3.1 available.
> /mnt/home/kwc/my_venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516:
> FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
> deprecated; in a future version of numpy, it will be understood as (type,
> (1,)) / '(1,)ty\
> pe'.
>   _np_qint8 = np.dtype([("qint8", np.int8, 1)])
> /mnt/home/kwc/my_venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517:
> FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
> deprecated; in a future version of numpy, it will be understood as (type,
> (1,)) / '(1,)ty\
> pe'.
>   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
> /mnt/home/kwc/my_venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518:
> FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
> deprecated; in a future version of numpy, it will be understood as (type,
> (1,)) / '(1,)ty\
> pe'.
>   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
> /mnt/home/kwc/my_venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519:
> FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
> deprecated; in a future version of numpy, it will be understood as (type,
> (1,)) / '(1,)ty\
> pe'.
>   _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
> /mnt/home/kwc/my_venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520:
> FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
> deprecated; in a future version of numpy, it will be understood as (type,
> (1,)) / '(1,)ty\
> pe'.
>   _np_qint32 = np.dtype([("qint32", np.int32, 1)])
> /mnt/home/kwc/my_venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525:
> FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
> deprecated; in a future version of numpy, it will be understood as (type,
> (1,)) / '(1,)ty\
> pe'.
>   np_resource = np.dtype([("resource", np.ubyte, 1)])
> /mnt/home/kwc/my_venv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541:
> FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
> deprecated; in a future version of numpy, it will be understood as (type,
> (1,)) / \
> '(1,)type'.
>   _np_qint8 = np.dtype([("qint8", np.int8, 1)])
> /mnt/home/kwc/my_venv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542:
> FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
> deprecated; in a future version of numpy, it will be understood as (type,
> (1,)) / \
> '(1,)type'.
>   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
> /mnt/home/kwc/my_venv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543:
> FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
> deprecated; in a future version of numpy, it will be understood as (type,
> (1,)) / \
> '(1,)type'.
>   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
> /mnt/home/kwc/my_venv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544:
> FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
> deprecated; in a future version of numpy, it will be understood as (type,
> (1,)) / \
> '(1,)type'.
>   _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
> /mnt/home/kwc/my_venv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545:
> FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
> deprecated; in a future version of numpy, it will be understood as (type,
> (1,)) / \
> '(1,)type'.
>   _np_qint32 = np.dtype([("qint32", np.int32, 1)])
> /mnt/home/kwc/my_venv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550:
> FutureWarning: Passing (type, 1) or '1type' as a synonym of type is
> deprecated; in a future version of numpy, it will be understood as (type,
> (1,)) / \
> '(1,)type'.
>   np_resource = np.dtype([("resource", np.ubyte, 1)])
> 08/03 07:43:06 AM: Loading config from jiant/config/tutorial.conf
> 08/03 07:43:06 AM: Config overrides: exp_name = my_exp, run_name = foobar
> 08/03 07:43:06 AM: Fatal error in main():
> Traceback (most recent call last):
>   File
> "/mnt/home/kwc/my_venv/lib/python3.6/site-packages/pyhocon/config_parser.py",
> line 450, in _resolve_variable
>     return True, config.get(variable)
>   File
> "/mnt/home/kwc/my_venv/lib/python3.6/site-packages/pyhocon/config_tree.py",
> line 209, in get
>     return self._get(ConfigTree.parse_key(key), 0, default)
>   File
> "/mnt/home/kwc/my_venv/lib/python3.6/site-packages/pyhocon/config_tree.py",
> line 151, in _get
>     raise ConfigMissingException(u"No configuration setting found for key
> {key}".format(key='.'.join(key_path[:key_index + 1])))
> pyhocon.exceptions.ConfigMissingException: 'No configuration setting found
> for key JIANT_PROJECT_PREFIX'

**Comment by sleepinyourhat** [comment]
- What package issues are you hitting? If you do the suggested `conda env create -f environment.yml; conda activate jiant
` from the tutorial, that should install everything you need. 
- I'm not sure I recognize the pyhocon issue that you're hitting. It might be subtly package related, but if not, we'll have to take a deeper look. @HaokunLiu @zphang @phu-pmh, have you seen an error like this?

**Comment by kwchurch** [comment]
got past that.  needed to export those variables

can you add something to the doc about installing the 3 python packages
(and exporting the variables)

**Comment by sleepinyourhat** [comment]
Thanks. I'll clarify the point about the export, but I'm not sure I understand the pip issue. The tutorial is based on conda, and the conda dependencies file (environment.yml) includes those three dependencies, so if the conda installation goes as we expect, you shouldn't have to run pip. 

Did you try to install through conda, and if so, did you see any major errors? 

For a bit more context, in case it helps, here's the  dockerfile that we use when running integration tests to ensure that jiant installs/runs as expected—after the first few lines, it's just a series of download/install commands that should line up with the tutorial.

**Comment by kwchurch** [comment]
Sorry, both conda and docker are discouraged on our cluster.  I should have
looked at the environment.yml file for pip dependencies

Don't see the docker file that you mentioned, but that would have been a
problem to run on our cluster as well.

The problem was that I failed to export the env variables.  Maybe you could
add that.

It would be good to remove as many dependencies as possible.  Not sure we
need conda or docker to make this stuff work.

**Comment by sleepinyourhat** [comment]
Oops—here = https://github.com/nyu-mll/jiant/blob/master/Dockerfile

I'll clarify about the env variables, and mention that using pip will require some reverse-engineering based on the conda yml. Thanks for the details!
