### ISSUE TITLE
problem extracting the POS data from the ontonotes corpus

### ISSUE THREAD

**Issue by lovodkin93** [nyu-mll/jiant#1108]
Hello,
I'm trying to extract the POS data from the ontonotes corpus by using the script python extract_ontonotes_all.py, based on the example in the README file which is in the directory probing/data, meaning the command I run is:
python extract_ontonotes_all.py --ontonotes /path/to/conll-formatted-ontonotes-5.0   --tasks pos   --splits train development test conll-2012-test   -o $JIANT_DATA_DIR/edges/ontonotes

And I'm getting the following error:

_08/08 09:54:50 AM: Processing split 'train' for task 'pos'
0it [00:00, ?it/s]08/08 09:54:50 AM: Reading CONLL sentences from dataset files at: /path/to/conll-formatted-ontonotes-5.0/data/train
0it [00:00, ?it/s]
08/08 09:54:50 AM: Wrote examples to /cs/labs/oabend/lovodkin93/jiant_rep/jiant-ep_frozen_20190723/data/edges/ontonotes/pos/train.json
Traceback (most recent call last):
  File "extract_ontonotes_all.py", line 203, in <module>
    main(sys.argv[1:])
  File "extract_ontonotes_all.py", line 198, in main
    log.info(stats.format())
  File "/cs/labs/oabend/lovodkin93/jiant_rep/jiant-ep_frozen_20190723/probing/data/utils.py", line 95, in format
    s = self.to_series(**kw)
  File "/cs/labs/oabend/lovodkin93/jiant_rep/jiant-ep_frozen_20190723/probing/data/utils.py", line 82, in to_series
    s["token.mean_count"] = stats["token.count"] / stats["count"]
ZeroDivisionError: division by zero_

I do have to say that when i extracted const, srl, coref and ner data, it worked perfectly, which is why i find it so weird that it doesn't work with pos.
Has anyone encountered a similar problem?
Thanks!

**Comment by sleepinyourhat** [comment]
Hrm. @iftenney, @zphang, @HaokunLiu - Have any of you seen something like this? @jeswan - Do we have a similar tool in jiant 2 alpha that you've tested?

**Comment by lovodkin93** [comment]
so after wrecking my brains, and going through the extraction code, i found the issue:
apparently, when extracting the data, there is no unique option for the pos (and the dependency trees if i am not mistaken), but in fact when using the const option, it consists of  pos and nonterminals, so it is possible to run pos experiments.
