### ISSUE TITLE
Reproducing GLUE paper single task results 

### ISSUE THREAD

**Issue by hsajjad** [nyu-mll/jiant#1110]
I am trying to reproduce the results presented in table 6 of GLUE paper. I am mainly interested in **single-task** bilstm training from scratch which is the first line in the table. I have tried various settings with embeddings trained from scratch or using Glove 840B embedding with single and multi-task but I am unable to produce or even come close to the results presented in table 6.
 
Do you have a configuration file that can reproduce these results?

**Comment by sleepinyourhat** [comment]
Hi! If you want the exact code from the leaderboard baselines, look here: https://github.com/nyu-mll/GLUE-baselines
