### ISSUE TITLE
not able to run single task copa example

### ISSUE THREAD

**Issue by isspek** [nyu-mll/jiant#1130]
Firstly, thank you so much for this framework! I try to run copa single task experiments` jiant/config/examples/copa_bert.conf`. The console gives the following exception:
```

    maybe_make_dir(args.project_dir)  # e.g. /nfs/jsalt/exp/$HOSTNAME
AttributeError: 'Params' object has no attribute 'project_dir'
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    raise e  # re-raise exception, in case debugger is attached.
  File "main.py", line 16, in <module>
    main(sys.argv[1:])
  File "/home/isspek/Project_Codes/jiant/jiant/__main__.py", line 572, in main
    args, seed = initial_setup(args, cl_args)
  File "/home/isspek/Project_Codes/jiant/jiant/__main__.py", line 375, in initial_setup
    maybe_make_dir(args.project_dir)  # e.g. /nfs/jsalt/exp/$HOSTNAME
AttributeError: 'Params' object has no attribute 'project_dir'
```

I also checked whether my custom project configurations work, but I am enable to run the following demo code `python main.py --config_file jiant/config/demo.conf     --overrides "exp_name = my_exp, run_name = foobar, d_hid = 256"`

I would appreciate to know what am I missing. 

Thanks in advance.

**Comment by sleepinyourhat** [comment]
Hi!

It looks like you don't have a working directory set for things like checkpoints. The typical way to do that is through the environment variable '$JIANT_PROJECT_PREFIX', as described in part 2 here:

https://github.com/nyu-mll/jiant/blob/master/tutorials/setup_tutorial.md

If that's hard to get working, it's also possible to manually add something like ', project_dir = /home/myusername/...' as another argument to --overrides.

**Comment by isspek** [comment]
I tried again and it didn't work. But I checked the logs, found the following issue:
```
10/07 05:32:47 PM: Cannot include file jiant/config/examples/defaults.conf. File does not exist or cannot be read.
10/07 05:32:47 PM: Fatal error in main():
```
After adding defaults.conf to /examples folder, I am able to run the demo.
