### ISSUE TITLE
Installing jiant from PyPi or source fails

### ISSUE THREAD

**Issue by jarednielsen** [nyu-mll/jiant#1140]
**Describe the bug**
I'm unable to install jiant from PyPi or from source. Below I've detailed how to replicate both these scenarios. It appears that the `setup.py` is written incorrectly, because installing `jiant` from PyPi gives you an empty package.

**Reproducing the PyPi Failure**
```bash
python --version # 3.7.6
python -m pip install jiant
python -c "import jiant"
# Traceback (most recent call last):
#  File "<string>", line 1, in <module>
# ModuleNotFoundError: No module named 'jiant'
```

If we inspect `ls -l /home/ubuntu/anaconda3/lib/python3.7/site-packages`, we see that the `.dist-info` directory is created, but the directory containing the `jiant` distribution is not. Compare this with the correct setup for the `jeepney` package. This is likely why the import fails.

```bash
drwxrwxr-x  5 ubuntu ubuntu     4096 Sep 12 00:37 jeepney
drwxrwxr-x  2 ubuntu ubuntu     4096 Sep 12 00:37 jeepney-0.4.2.dist-info
drwxrwxr-x  2 ubuntu ubuntu     4096 Oct  8 23:02 jiant-2.0.0.dist-info
```

**Reproducing Build from Source Failure**
```bash
git clone https://github.com/nyu-mll/jiant
cd jiant
python -m pip install -e .
python -c "import jiant; print(dir(jiant))" # succeeds, but the jiant namespace has no members
# ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
cd /home
python -c "import jiant"
# Traceback (most recent call last):
#  File "<string>", line 1, in <module>
# ModuleNotFoundError: No module named 'jiant'
```

Here the file `/home/ubuntu/anaconda3/lib/python3.7/site-packages/jiant.egg-link` is created.

**Comment by jeswan** [comment]
Thanks for reporting this! Looking into this now.

**Comment by jeswan** [comment]
Just uploaded the fixed package to PyPi. Let me know if you are still seeing any issues.

**Comment by jarednielsen** [comment]
The latest version works, thanks!
