### ISSUE TITLE
How to import my own model?

### ISSUE THREAD

**Issue by HyeondeyKim** [nyu-mll/jiant#1174]
I want to import my own pre-trained model which is already fine-tuned to another tasks.

Is it possible to load my own model? what is the different between p file and pt file ?

**Comment by thak123** [comment]
Hi ... I want to have my custom model in the multi task architecture, is it possible

**Comment by jeswan** [comment]
@thak123 Are you using Hugging Face? I am currently working on a change to make it easy to add a Hugging Face supported transformer model to the library (ie: MobileBERT - https://github.com/nyu-mll/jiant/pull/1274/files)
