### ISSUE TITLE
TimeDistributed

### ISSUE THREAD

**Issue by terarachang** [nyu-mll/jiant#1209]
Hi,

I have a question about the usage of the TimeDistributed class in:
https://github.com/nyu-mll/jiant/blob/6e6e8d49c7c49f2f726c2ce5c1d23ecd338fd67c/jiant/ext/allennlp.py#L36

I would like to know if it's necessary to wrap the module in this class.
I'm training the EP tasks and I've tried:
```
	self.ln = torch.nn.Linear(input_dim, 1)
	self._global_attention = TimeDistributed(self.ln)

	global_attention_logits = self._global_attention(sequence_tensor)
	my_attention_logits = self.ln(sequence_tensor)
	assert (my_attention_logits-global_attention_logits).sum() == 0
```

It seems like the two are equivalent.

Thanks!

**Comment by jeswan** [comment]
The `TimeDistributed` class is borrowed from https://github.com/allenai/allennlp/blob/b792c834b5f70122c7c296ded7c97ac974cda6f4/allennlp/modules/time_distributed.py#L13. The docstring in the link may give you more context. Let me know if you have additional questions.

**Comment by terarachang** [comment]
Got it! Thanks!
