### ISSUE TITLE
Add preprocessing scripts for quail

### ISSUE THREAD

**Issue by jeswan** [nyu-mll/jiant#1226]
**Is your feature request related to a problem? Please describe.**
The preprocessing scripts are missing for the quail task. 

**Describe the solution you'd like**
Add the preprocessing scripts to `jiant` so that the task can be run without external scripts.

**Context**
https://github.com/nyu-mll/jiant/pull/1208#event-3951230828

**Comment by claravania** [comment]
Close with https://github.com/nyu-mll/jiant/pull/1258.
