### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by Bosheng2020** [nyu-mll/jiant#1230]
I have followed the examples in the jiant github but both of us have found this problem as shown in the screenshot below:

<img width="1323" alt="Screenshot 2020-11-10 at 11 08 38 AM" src="https://user-images.githubusercontent.com/59857658/98625408-81f80800-234a-11eb-8c00-1fcb88938707.png">

It seems the code below has some problem and thus cause the data and config files can't be downloaded. I have copied it from the examples provided in the jiant github.

<img width="1117" alt="Screenshot 2020-11-10 at 11 48 08 AM" src="https://user-images.githubusercontent.com/59857658/98625472-a05e0380-234a-11eb-9a51-cd7d7409800e.png">

Could you kindly help us clarify on this problem?

**Comment by zphang** [comment]
Hey, sorry for the inconvenience. We've fixed the example (we needed to add a `%cd ..` near the top) in https://github.com/nyu-mll/jiant/pull/1231. If you open a new session with the updated Colab notebook, the script should work now.

You might also want to check out some slightly newer versions of the examples that we're working on:

- [Simple API](https://colab.research.google.com/drive/1kKHNuNXmZfOPOX69FVU_8jI1D06mz2FP?usp=sharing)
- [Main API](https://colab.research.google.com/drive/1kKHNuNXmZfOPOX69FVU_8jI1D06mz2FP?usp=sharing)

Let us know if you're still encountering issues!
