### ISSUE TITLE
mnli_mismatched, this task does not support training exemples 

### ISSUE THREAD

**Issue by smolPixel** [nyu-mll/jiant#1235]
Installed jiant via command line (pip3). Changing the task name I can run mrpc, sst, stsb, cola, and mnli, but mnli_mistmached gives me the error 
Traceback (most recent call last):
  File "run_glue_bert.py", line 38, in <module>
    simple_run.run_simple(args)
  File "/u/username/Documents/DAGlue/venv/lib/python3.7/site-packages/jiant/proj/simple/runscript.py", line 158, in run_simple
    do_iter=True,
  File "/u/usernam/Documents/DAGlue/venv/lib/python3.7/site-packages/jiant/proj/main/tokenize_and_cache.py", line 165, in main
    examples=task.get_train_examples(),
  File "/u/username/Documents/DAGlue/venv/lib/python3.7/site-packages/jiant/tasks/lib/mnli_mismatched.py", line 28, in get_train_examples
    raise RuntimeError("This task does not support training examples")
RuntimeError: This task does not support training examples

The code is below (changed the data directories and username but I doubt that's the source of the problem)

`import os

import jiant.proj.simple.runscript as simple_run
import jiant.scripts.download_data.runscript as downloader
#See https://github.com/nyu-mll/jiant/blob/master/guides/tasks/supported_tasks.md for supported tasks
#TASK_NAME = ["mrpc", "sst", "stsb", "wnli", "cola", "glue_diagnostics", "mnli", "mnli_mismatched", "qnli", "qqp", "rte", ]
TASK_NAME="mnli_mismatched"

#See https://huggingface.co/models for supported models
MODEL_TYPE = "bert-base-uncased"

RUN_NAME = f"simple_{TASK_NAME}_{MODEL_TYPE}"
EXP_DIR='GLUE'
DATA_DIR='GLUE/data'

os.makedirs(DATA_DIR, exist_ok=True)
os.makedirs(EXP_DIR, exist_ok=True)

downloader.download_data([TASK_NAME], DATA_DIR)

args = simple_run.RunConfiguration(
    run_name=RUN_NAME,
    exp_dir=EXP_DIR,
    data_dir=DATA_DIR,
    model_type=MODEL_TYPE,
    tasks=TASK_NAME,
    train_batch_size=32,
    num_train_epochs=4
)
simple_run.run_simple(args)

Any idea of what I should do? Thanks

**Comment by sleepinyourhat** [comment]
MNLI mismatched is an OOD evaluation set for MNLI (genres that are 'mismatched' to the training set), so the error is correct: It has no training examples. You'll have to train on MNLI.

**Comment by smolPixel** [comment]
Hi, thanks for your answer. Sorry to be bugging you but I'm trying to run baseline on GLUE and the documentation is outdated (I cant find the documentation for Jiant 2 and cant find an answer in Jiant 1 docu). What is the simplest way to evaluate on MNLI_mismatched? thanks

**Comment by sleepinyourhat** [comment]
I'm not certain of the exact right command (CC @zphang), but I _think_ you should be able to just add "mnli" to the task list.

**Comment by jeswan** [comment]
[This notebook](https://colab.research.google.com/github/nyu-mll/jiant/blob/master/examples/notebooks/jiant_MNLI_Diagnostic_Example.ipynb) has an example of training on mnli and evaluating on mnli-mismatched.

**Comment by smolPixel** [comment]
Yes this looks like it has everything I need, must have missed it! Thank you very much :)
