### ISSUE TITLE
Update to Transformers v4

### ISSUE THREAD

**Issue by jeswan** [nyu-mll/jiant#1236]
Transformers v4 has several breaking changes captured here: https://github.com/huggingface/transformers/releases/tag/v4.0.0-rc-1

Transformers now uses fast (rust) tokenizers by default. This is a desirable feature for `jiant`. If the update to Transformers v4 does not include the switch to fast tokenizers, another issue should be created to capture this work.

**Comment by zphang** [comment]
I'm a little more concerned about the model-reorganization. Might be a good time to revisit our model / ModelArchitecture setup altogether. This sounds like something I could tackle over the EOY break.
