### ISSUE TITLE
Can I use my own datasets ?

### ISSUE THREAD

**Issue by SivaAndMe** [nyu-mll/jiant#1254]
Hi, I'm entirely new to Jiant. I was trying to find a way to train a model on my own datasets but in vain.  Does Jiant support this feature? If yes, please guide me to an example.

Thanks

**Comment by jeswan** [comment]
Please see the following guide for adding your own dataset to `jiant`: https://github.com/nyu-mll/jiant/blob/master/guides/tasks/adding_tasks.md

**Comment by SivaAndMe** [comment]
@jeswan, Thank You. It's helpful.
