### ISSUE TITLE
How to compute the score GPS for AXG

### ISSUE THREAD

**Issue by juliahane** [nyu-mll/jiant#1269]
Hi
I need to compute GPS score for AXG dataset, could you assist me please and share me the implementation of this metric? 
Since labels are given, I hope I can get the metric function and run it locally to avoid overhead of submission to an online system? thanks

**Comment by pruksmhc** [comment]
The metric is implemented here: https://github.com/nyu-mll/jiant-v1-legacy/blob/99d0900afdf3949196be7fda907aac6075a1370d/jiant/metrics/winogender_metrics.py .
