### ISSUE TITLE
How to load datasets from local path?

### ISSUE THREAD

**Issue by ast123** [nyu-mll/jiant#1276]
Thank  you for your effort in developing this library!
I apologize if this has been addressed elsewhere. I have been looking into the source codes and I would like some guidance on what to do in order to run experiments using custom datasets which are stored locally on disk. Thank you!

**Comment by jeswan** [comment]
Thanks for using the library! 

To add a custom task, see the README here: https://github.com/nyu-mll/jiant/blob/master/guides/tasks/adding_tasks.md. 

To run the custom dataset stored locally, a task data config object needs to be generated. Please see the output of the _Download Data_ step here: https://colab.research.google.com/github/nyu-mll/jiant/blob/master/examples/notebooks/jiant_Basic_Example.ipynb. This task config object is used in the next step to tokenize the data:

```
tokenize_and_cache.main(tokenize_and_cache.RunConfiguration(
    task_config_path=f"./tasks/configs/{task_name}_config.json")
```
