### ISSUE TITLE
Tutorial Notebooks and Installations do not work

### ISSUE THREAD

**Issue by teshnizi** [nyu-mll/jiant#1279]
**Describe the bug**
Hi,

I have been trying a handful of the example notebooks. None of them is working properly on Google Colab, resulting in this error:
`AttributeError: module 'jiant' has no attribute 'tasks'`
![Screenshot from 2021-02-08 15-39-03](https://user-images.githubusercontent.com/48642434/107217735-da12d900-6a23-11eb-93f1-3639c3233e40.png)

**To Reproduce**

Simply go to any of the example notebooks (The picture is from [this](https://github.com/nyu-mll/jiant/blob/master/examples/notebooks/jiant_Multi_Task_Example.ipynb) one), copy and paste the commands into Google Colab and try executing them). The Colab instance you have shared also seems not to be working.

**Comment by zphang** [comment]
Hi @teshnizi, just to confirm, are you running the above cells before running the cell you've highlighting, as well as the cell modifying the `sys.path` right before?

**Comment by teshnizi** [comment]
Hi,
Yes. I run the following cells:

![screencapture-colab-research-google-drive-10u4n-HIFOL02QeeHuLucSCZlemvuEXPC-2021-02-09-11_33_15](https://user-images.githubusercontent.com/48642434/107333524-dab27a80-6aca-11eb-8399-46f31509c9a8.png)

 I am not modifying the syspath line though, as '/content/jiant/' seems like to be the right path when I'm using Colab. I do not face this problem when I use pip for installation.

**Comment by zphang** [comment]
Hi @teshnizi, can you try running it again now? I've pushed an update to the code (#1282). Basically, the issue was some circular imports that aren't handled properly in Python 3.6.9 (#1167).

**Comment by teshnizi** [comment]
It seems to be working now. Thank you!
