### ISSUE TITLE
README.md "Quick Introduction" is broken

### ISSUE THREAD

**Issue by eritain** [nyu-mll/jiant#1280]
**Describe the bug**
Documentation directs brand-new users to download task data to one place and read it from another. 

**To Reproduce**
Follow the "Python version" quick introduction instructions as seen in the README. In particular,

```python
downloader.download_data(["mrpc"], "/content/data")
```

do that line as written, if you even have write permission on your root dir. If you don't, use some approximation of `/content/data` that you can write to, and wonder if you're breaking something. You *are* breaking something, but not because you deviated too *far* from `/content/data`. 

Continue with the rest of the instructions. `tokenize_and_cache.py` will die because the MRPC data aren't in `${EXP_DIR}/tasks`. 

**Expected behavior**
Jiant fine-tunes a pretrained RoBERTa on MRPC.

**Additional context**
This is not the only way to break `tokenize_and_cache` from the downloader, but a separate issue will be filed on that.

**Comment by zphang** [comment]
Hi @eritain, thanks so much for your feedback. I've updated the documentation with #1282.
