### ISSUE TITLE
Ability to define custom models 

### ISSUE THREAD

**Issue by thak123** [nyu-mll/jiant#1284]
Hi 

I am planning to implement custom models on top of transformers but not using the in built classification functions.

Is this possible using the Jiant ?

**Comment by jeswan** [comment]
That should be possible. You can define your task-specific head by adding a new head to the registry (currently WIP but you can work off the feature branch here): https://github.com/nyu-mll/jiant/commit/e004af87be87422d53d7360cfe30da2bafca65e7

It is easiest to use models that are classes/subclasses of Transformers models. Let me know if you run into issues while implementing your model.

**Comment by thak123** [comment]
Thanks for the pointer @jeswan
