### ISSUE TITLE
Error in jiant_MNLI_Diagnostic_Example.ipynb?

### ISSUE THREAD

**Issue by eritain** [nyu-mll/jiant#1292]
The notebook reads, 

> Configure all three tasks to use an `mnli` head.

followed by 

```
jiant_run_config["taskmodels_config"]["task_to_taskmodel_map"] = {
    "mnli": "mnli",
    "mnli_mismatched": "mnli",
    "glue_diagnostics": "glue_diagnostics",
}
```

By analogy with jiant_XNLI_Example.ipynb one would expect "glue_diagnostics": ~"glue_diagnostics"~ **"mnli"**". Is this correct?

**Comment by zphang** [comment]
Good catch, that's correct. I will push a fix here: https://github.com/nyu-mll/jiant/pull/1294
