### ISSUE TITLE
DeBERTa support

### ISSUE THREAD

**Issue by zabh0z** [nyu-mll/jiant#1293]
It seems like the newest transformers `AutoModel` supports DeBERTa
(you can find it on AutoModel page https://huggingface.co/transformers/model_doc/auto.html#transformers.AutoModel)

The transformers version that is required by `jiant` (transformers==3.1.0) doesn't support DeBERTa

So I installed the newest transformers 4.4.0 and `jiant` doesn't support it and fails with the following error message

```
  File "/jiant/jiant/tasks/lib/templates/squad_style/core.py", line 8, in <module>
    from transformers.tokenization_bert import whitespace_tokenize                                                                                                                                                                     
ModuleNotFoundError: No module named 'transformers.tokenization_bert'
```

I wonder what's the easiest way to integrate the DeBERTa support?

Thank you!

**Comment by jeswan** [comment]
I am currently working on adding DeBERTa here: https://github.com/nyu-mll/jiant/commit/12a34b356c16f08dcbc4d5ff81dc59de17c23624 (this depends on a large refactor to make it easy to add a model). Note this branch is a work in progress.

**Comment by zabh0z** [comment]
@jeswan Thank you for the fast response!
