### ISSUE TITLE
typo in supported_tasks.md?

### ISSUE THREAD

**Issue by eritain** [nyu-mll/jiant#1299]
`guides/tasks/supported_tasks.md` lists `superglue_axg` as the task name for both the SuperGLUE Winogender Diagnostic and the SuperGLUE Broad Coverage Diagnostic. Should the latter be `superglue_axb`?

**Comment by zphang** [comment]
Thanks! That's sounds right, PR: https://github.com/nyu-mll/jiant/pull/1300
