### ISSUE TITLE
Google Colab Error

### ISSUE THREAD

**Issue by Harry-Rogers** [nyu-mll/jiant#1310]
**Describe the bug**
I have encountered this TypeError in the colab simple_api_fine_tuning book. I have not changed anything in the book just tried to run it. The checout tag is 2.0.0

![image](https://user-images.githubusercontent.com/35311763/115966253-97da3d80-a524-11eb-8c10-77f10dae5002.png)

**Comment by gokejian** [comment]
This "model_type" parameter should be changed to "hf_pretrained_model_name_or_path". I encountered this before.  Please check the latest README at the jiant GitHub page.
