### ISSUE TITLE
Error in data download while converting conllu files to conll format 

### ISSUE THREAD

**Issue by dapurv5** [nyu-mll/jiant#1324]
**Issue**
Trying to run the data download script for xtreme benchmark. I am following the [README.md](https://github.com/nyu-mll/jiant/blob/master/guides/benchmarks/xtreme.md)

I run the download command as
```
python ~/jiant/jiant/scripts/download_data/runscript.py download --benchmark XTREME --output_path ${BASE_PATH}/tasks/
```

While Converting conllu files to conll format I run into the following error.

```
   task_data_base_path=task_data_base_path, task_config_base_path=task_config_base_path,
  File "/home/ec2-user/jiant/jiant/scripts/download_data/dl_datasets/xtreme.py", line 205, in download_udpos_data_and_write_config
    remove_arabic_diacritics=False,
  File "/home/ec2-user/xtremej/tasks/data/udpos_temp/conll.py", line 234, in filter_sentence_content
    self._keep_fused_form(posPreferenceDict)
  File "/home/ec2-user/xtremej/tasks/data/udpos_temp/conll.py", line 192, in _keep_fused_form
    for ext_dep in depdict[localhead]:
TypeError: 'generator' object is not subscriptable
```

**To Reproduce**
mainline 310f22b515211f2e8fc8d229e196ce520557742d

Am I missing something?

**Comment by zphang** [comment]
The CoNLL preprocessing script is downloaded on the fly, and it looks like it was modified upstream. I've pushed a change to pin the version of the script downloaded (https://github.com/nyu-mll/jiant/pull/1326). Please pull and try again. Also, confirm that you are using `networkx==1.11`.

**Comment by dapurv5** [comment]
Thanks for your fix. It works now. Thank you for maintaining this great repo.
