### ISSUE TITLE
Make sure we _don't_ reuse task parameters between pretraining and target task training.

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#290]
For GLUE, this introduces an inconsistency between tasks with attention (where we have different models during pretraining and task training), and tasks without (where we use the same model, and keep the parameters in most cases).

Current plan is to fix this and re-run the impacted run. But the impact on performance should be tiny, so safe to start analysis now as long as its possible to re-run. 

Easiest version of a fix: Create an 'alt' version of every GLUE task that we can use for pretraining (similar to what @berlinchen7 and I did for attention experiments). Can anyone think of a better fix?

**Comment by W4ngatang** [comment]
Isn't this fixed? We have a flag that must be explicitly turned on to reuse pretraining parameters (`allow_reuse_of_pretraining_parameters`) and we have alternate versions of each GLUE task so you can easily do the right thing here.
