### ISSUE TITLE
Precompute and cache ELMo vectors

### ISSUE THREAD

**Issue by W4ngatang** [nyu-mll/jiant#333]
AllenNLP has an implementation of precomputing and caching word vectors so we don't need to run the model every time. This will save us GPU memory and processing time: 

https://github.com/allenai/allennlp/blob/master/allennlp/modules/elmo.py#L63

**Comment by sleepinyourhat** [comment]
Probably not worth a ton of effort, as I suspect new large-scale experiments are unlikely to use full ELMo. (Though we should keep it around for smaller-scale experiments.)
