### ISSUE TITLE
Demo runs not deterministic anymore

### ISSUE THREAD

**Issue by iftenney** [nyu-mll/jiant#360]
I'm now seeing variation on the order of +/- 1% between demo runs(demo.conf and edgeprobe_demo.conf) with identical configuration. When I last checked this a few weeks ago, I would get exactly the same numbers each time.

Did we make any recent changes that affect the random seeds? It's also possible that I've messed up the dev environment on my workstation. I'll follow up here with more tests.

**Comment by pyeres** [comment]
Heads up: some run-to-run variation was smoothed out w/ #991. Is this still an issue for anyone?

**Comment by pyeres** [comment]
As part of a recent PR I compared the logs for demo.conf before and after a change: [here](https://github.com/nyu-mll/jiant/pull/1080#issuecomment-620955946).

The results were the same, so I'm closing this issue as resolved.
