### ISSUE TITLE
Undefined name may raise NameError at runtime

### ISSUE THREAD

**Issue by cclauss** [nyu-mll/jiant#414]
[flake8](http://flake8.pycqa.org) testing of https://github.com/jsalt18-sentence-repl/jiant on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./src/tasks.py:2204:22: F821 undefined name 'cos_sim'
            metric = cos_sim(np.asarray(np1), np.asarray(np2))[0][0]
                     ^
./src/tasks.py:2314:22: F821 undefined name 'cos_sim'
            metric = cos_sim(np.asarray(np1), np.asarray(np2))[0][0]
                     ^
./src/preprocess.py:480:17: F821 undefined name 'update_target_vocab_freqs'
                update_target_vocab_freqs(sentence)
                ^
./src/edge_probing.py:207:52: F821 undefined name 'loss_type'
                             "for edge probing." % loss_type)
                                                   ^
./src/allennlp_mods/elmo_text_field_embedder.py:55:9: F821 undefined name 'self'
        self._elmo = Elmo.from_params(params)
        ^
./src/allennlp_mods/elmo_text_field_embedder.py:56:16: F821 undefined name 'self'
        return self
               ^
6     F821 undefined name 'self'
6
```

**Comment by sleepinyourhat** [comment]
Eek. Are you hitting these lines in any normal experimental setups?

**Comment by cclauss** [comment]
I am not hitting these lines other than with flake8.  Often undefined names are in dead code or in __except__ blocks that do not have test cases.  They are missing __import__ statements (the first three above?) where another Python file has already loaded the module in question.  These are like ticking time mobs when code changes.  Perhaps this is one of the sources of the “_Explict is better than implicit._” line in the Zen of Python.
