### ISSUE TITLE
Clean up modules.py

### ISSUE THREAD

**Issue by iftenney** [nyu-mll/jiant#420]
I won't get to this until after the ICLR deadline, but I'd like to clean up the `src/` directory so dependencies are a bit cleaner. Also, `tasks.py` is massive and we should really split it up.

Proposed structure:
```
src/
    allennlp_mods/
    cove/ [submodule]
    __init__.py
    evaluate.py
    models.py
    modules/
        cnns/
        __init__.py
        <several .py files with old contents of modules.py>
        edge_probing.py
        seq2seq_decoder.py
        generate_s2s.py
    preprocess.py
    tasks/
        __init__.py
        tasks.py    # core definitions and registry
        edge_probing.py
        <other .py files containing various groups of tasks>
    trainer.py
    utils/    # or "misc/" or "lib/"
        __init__.py
        config.py
        emails.py
        gcp.py
        hocon_writer.py
        retokenize.py
        serialize.py
        utils.py
```

**Comment by sleepinyourhat** [comment]
SGTM!

**Comment by W4ngatang** [comment]
I'm all for it

**Comment by iftenney** [comment]
Most of this is done now, but we might want to still split up `modules.py`. I shied away from doing this because of potential bugs this close to the NAACL deadline, but if someone (@W4ngatang maybe?) who knows this code better than I wants to take a stab at it, we could merge later in December.

**Comment by sleepinyourhat** [comment]
What's left to do, @iftenney?
