### ISSUE TITLE
Multi-GPU training support

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#446]

**Comment by sleepinyourhat** [comment]
cc @iftenney

**Comment by sleepinyourhat** [comment]
It looks like the Allen fundamentals all support this, though with some caveats: https://github.com/allenai/allennlp/issues/2127

This is becoming increasingly urgent with BERT Large and XLNet—we can't use them at full sequence length on commodity GPUs.

**Comment by HaokunLiu** [comment]
May I ask what’s the status of this thread? Do you need some extra hands?

**Comment by sleepinyourhat** [comment]
Check with @pruksmhc, but I don't think anything is happening with this now. If you want to try it, please do!

**Comment by pruksmhc** [comment]
@HaokunLiu I'm actually working on this and planning to release a PR early next week!

**Comment by HaokunLiu** [comment]
@pruksmhc  Oh, that's great. Thanks.
