### ISSUE TITLE
Set up automatic pep8 checking on PRs

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#464]

**Comment by pruksmhc** [comment]
Is this the pep8 plugin? https://github.com/apps/pep8-speaks @sleepinyourhat

**Comment by sleepinyourhat** [comment]
I didn't have a specific one in mind, but if you can use it to flag PRs that break pep8, then go for it.

**Comment by sleepinyourhat** [comment]
Aaaand this one looks kinda broken. Though if there are no better ones, I guess we can change to an 80-char line limit and autopep8 everything.

**Comment by sleepinyourhat** [comment]
Mind fixing this or turning it off soonish?

**Comment by sleepinyourhat** [comment]
Fixed.
