### ISSUE TITLE
Idle speculation: float16 support?

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#472]
I have no idea how big a project this would be, but it'd be nice to add the option to create models with float16 parameters and activations. I haven't used such models much, but my understanding is that you get a substantial speed/memory gain with very little performance/stability loss. The new Lample and Conneau noted that it was crucial for their work on multilingual BERT-style model training.

**Comment by sleepinyourhat** [comment]
See also: https://www.github.com/nvidia/apex

**Comment by pyeres** [comment]
Closing as superseded by issue #1048.
