### ISSUE TITLE
Replace OpenAI Transformer implementation with newer version

### ISSUE THREAD

**Issue by iftenney** [nyu-mll/jiant#491]
Latest version of [pytorch_pretrained_bert](https://github.com/huggingface/pytorch-pretrained-BERT#pytorch-pretrained-bert-the-big-and-extending-repository-of-pre-trained-transformers) package contains an implementation of the OpenAI GPT model. This package is much cleaner than the earlier one we were using, so we might save a lot of code by switching our support for the GPT model to this implementation.

See https://github.com/huggingface/pytorch-pretrained-BERT/releases/tag/v0.5.0

**Comment by iftenney** [comment]
Note: let's not do this until after the ACL deadline (March 4).

**Comment by pruksmhc** [comment]
Closed with #611
