### ISSUE TITLE
Add a list of supported tasks to the main README

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#509]
For prospective users, it'll help to advertise the target tasks that are fully supported out of the box (the GLUE tasks, plus a few others), and to mention additional tasks with partial/potential support (MT, image–caption matching, etc.).

**Comment by pruksmhc** [comment]
Started here 
https://github.com/nyu-mll/jiant
Will need to be updated as we have an influx of models right now
