### ISSUE TITLE
Support task data-loading for specific phases

### ISSUE THREAD

**Issue by zphang** [nyu-mll/jiant#515]
Expose method(s) for loading data for tasks corresponding to a specific phase, e.g. load training data for CoLA. Currently, loading is done for all phases at once. Ideally, we should have individual data loading for phases, and the `load_data` method can call the method(s) for loading every phase.

**Comment by sleepinyourhat** [comment]
Did you wind up making progress on this?

**Comment by pyeres** [comment]
Confirmed with @zphang — resolved.
