### ISSUE TITLE
Remove or hide fasttext model compatibility

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#523]
The fasttext _model component_ (as opposed to the mere embeddings file) isn't compatible with PyTorch out of the box. If you try to install it normally with conda, you'll cause jiant/PyTorch to segfault on import. That's what @alexwarstadt was hitting a couple of days ago.

It's possible to use it if you do a more complex custom installation, but it's very easy to mess up, and I don't expect that many people will use it. We should definitely remove any mention the fasttext model component from the readme/requirements, and it might be a good idea to remove support for it entirely.

**Comment by W4ngatang** [comment]
Removed with #583
