### ISSUE TITLE
'diagnostic-full.tsv' does not exist

### ISSUE THREAD

**Issue by Bogerchen** [nyu-mll/jiant#555]
diagnostic-full.tsv is not downloaded after running download_glue_data.py. So, when setting pretrain_tasks= glue, FileNotFoundError raises. The full error is:
FileNotFoundError: File b'/data/ChenCB/jiant/data/MNLI/diagnostic-full.tsv' does not exist.

**Comment by sleepinyourhat** [comment]
Thanks for flagging this! Until we have a fix, you can download that file from here (linked in the 'Diagnostic' tab of the site):

https://www.dropbox.com/s/ju7d95ifb072q9f/diagnostic-full.tsv?dl=1

**Comment by sleepinyourhat** [comment]
Merging this with #495. Hopefully we can fix this this week...
