### ISSUE TITLE
Missing predictions for MNLI

### ISSUE THREAD

**Issue by Bogerchen** [nyu-mll/jiant#556]
The whole length for test_matched.tsv, test_mismatched.tsv, and diagnostic.tsv is 20747. But after loaded, the exact length turns into 20744. Snapshots of log information are shown below: 

04/18 10:45:09 AM:      Loaded existing task mnli
04/18 10:45:09 AM:      Task 'mnli': train=392662 val=19647 test=20744

Traceback (most recent call last):
  File "main.py", line 409, in <module>
    raise e  # re-raise exception, in case debugger is attached.
  File "main.py", line 399, in <module>
    main(sys.argv[1:])
  File "main.py", line 392, in main
    evaluate_and_write(args, model, target_tasks, splits_to_write)
  File "main.py", line 122, in evaluate_and_write
    strict_glue_format=args.write_strict_glue_format)
  File "/data/ChenCB/jiant/src/evaluate.py", line 137, in write_preds
    strict_glue_format=strict)
  File "/data/ChenCB/jiant/src/evaluate.py", line 272, in _write_glue_preds
    assert len(preds_df) == 20747, "Missing predictions for MNLI!"
AssertionError: Missing predictions for MNLI!

I guess maybe some test instances are removed during preprocessing?

**Comment by sleepinyourhat** [comment]
Hrm—sorry to hear this. I've never seen anything like this come up.

- Double check that the MNLI files are actually there and complete.
- Try deleting your experiment directory to force jiant to re-preprocess everything.
- If neither of those works, try to set up a minimum working example and post your config file and command here.

Best of luck!

**Comment by StephAO** [comment]
I also got this error too. @Bogerchen did you find a fix?

**Comment by sleepinyourhat** [comment]
We've simplified some of this code in 1.0. Is anyone still hitting this?

**Comment by pyeres** [comment]
Closing this as stale.
