### ISSUE TITLE
Checkpointing Logic Cleanup

### ISSUE THREAD

**Issue by pruksmhc** [nyu-mll/jiant#558]
Checkpointing logic is a little obtuse and scattered throughout files, and seems different for finetuning as a transfer paradigm versus frozen.

**Comment by W4ngatang** [comment]
Hmm, I'm not totally sure what this means. The logic for dealing with frozen/fine-tuning necessarily is different and is confined to `main.py`. The actual code for creating checkpoints I think is only in `trainer.py`?

**Comment by sleepinyourhat** [comment]
_Mostly_ addressed in #752.

**Comment by sleepinyourhat** [comment]
Though there's one biggish remaining issue: Make sure we support restoring a partially-completed target-task-phase training run.

**Comment by pruksmhc** [comment]
How granular do we want this to be? Would we want to track down to which example it was training on when it crashed, so we can resume training at exactly the same place it was before?

**Comment by sleepinyourhat** [comment]
We could follow exactly the same logic as in the pretraining phase, which is fairly standard: Load the last regular checkpoint (the most recent, not necessarily the best), and restore all training state from the checkpoint—model parameters, optimizer parameters, step count, etc.
