### ISSUE TITLE
RAIL (licence)

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#559]
What do people think about this (esp. @W4ngatang @pruksmhc @iftenney):

https://www.licenses.ai/ 

It could be nice to add, but if we do, I might delete the 'surveillance' clause. It's so broad that it'd probably prevent anyone from doing bias-related research using _jiant_.

**Comment by iftenney** [comment]
Potential concern: this might cause issues with industry collaborators who are subject to more stringent restrictions on OSS licensing.

**Comment by sleepinyourhat** [comment]
Hrm—do you have a sense of exactly how/where that'd come up?
