### ISSUE TITLE
Delete decoder code

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#566]
It seems to be abandoned by its authors, and there are major known issues (#371, #375

**Comment by phu-pmh** [comment]
The decoder is still used in `src\models.py` for `RedditSeq2SeqTask, Wiki103Seq2SeqTask` and `MTTask` (related to ACL submission?). It might still be needed.

**Comment by sleepinyourhat** [comment]
Still worth taking a look around to see if there's anywhere that we can/should add deprecation warnings.

**Comment by sleepinyourhat** [comment]
#781
