### ISSUE TITLE
Make pretrain_data_fraction and target_train_fraction independent

### ISSUE THREAD

**Issue by pruksmhc** [nyu-mll/jiant#570]
Right now, we don't fully support setting those two variables to anything other than default, and there are asserts to make sure that they aren't set. The code surrounding these two is still generally messy.

**Comment by pruksmhc** [comment]
There's also some pretty worrying comments like this one:
https://github.com/nyu-mll/jiant/blob/master/src/trainer.py#L288

**Comment by sleepinyourhat** [comment]
Still an open issue?

**Comment by BordiaS** [comment]
It was fixed in #641
