### ISSUE TITLE
Rename `src` -> `jiant`

### ISSUE THREAD

**Issue by W4ngatang** [nyu-mll/jiant#578]
This would be nice but will break lots of people's saved tasks (because pickles!). Let's save until after the May deadlines.

**Comment by sleepinyourhat** [comment]
Is anyone here working on anything with big/slow/expensive training runs?
Better to do this before the May 1 launch than after.

**Comment by sleepinyourhat** [comment]
#593

**Comment by sleepinyourhat** [comment]
Still on it? This is the last day I can do much reviewing before Mon.

**Comment by pruksmhc** [comment]
Done with https://github.com/nyu-mll/jiant/commit/230af2d44dd9e045bf69a253ffe98e11ad29c0a4
