### ISSUE TITLE
Clarify the status of 'warmup'

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#598]
From `defaults.conf`: 

`warmup = 4000  // Number of warmup steps for custom transformer LR schedule.`

We don't mention this optimizer anywhere but here. It needs a bit more documentation, assuming it's still supported.

**Comment by sleepinyourhat** [comment]
Still on it? This is the last day I can do much reviewing before Mon.

**Comment by W4ngatang** [comment]
Resolved with #804
