### ISSUE TITLE
A few example config files

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#605]
It'd be nice to put together a more deliberate set of config files, maybe corresponding to the tutorial(s), that demonstrate well-supported use cases, like training a CBOW baseline, STILTs-style training with BERT, or MTL with an LSTM.

**Comment by sleepinyourhat** [comment]
#669 is one.

**Comment by pruksmhc** [comment]
MTL with an LSTM is in the tutorial and involves tweaking the demo.conf very slightly (the demo.conf is MTL without LSTM). Should we have a separate one with LSTM?

**Comment by sleepinyourhat** [comment]
Seems reasonable!

**Comment by pruksmhc** [comment]
Examples are here: https://github.com/nyu-mll/jiant/tree/master/config/examples
