### ISSUE TITLE
Probing keywords

### ISSUE THREAD

**Issue by vincentschen** [nyu-mll/jiant#630]
Hello -- I was curious about the keywords used in the [probing](https://arxiv.org/abs/1904.11544) project. How did you segment your data into Definite-indefinite articles, Wh-Words, etc.

This seems like a relevant place to look, but I couldn't find the associated files or download instructions: https://github.com/nyu-mll/jiant/blob/master/scripts/move_preds_files.sh

**Comment by najoungkim** [comment]
Hi! The probing dataset / instructions to replicate the experiments will be updated soon (probably within this week!)

**Comment by sleepinyourhat** [comment]
@najoungkim - Safe to close this?

**Comment by najoungkim** [comment]
Most of the instructions are in place, but still waiting on official dataset release to add final preprocessing scripts. Might be better to keep it open until then?

________________________________

**Comment by sleepinyourhat** [comment]
When's then?

**Comment by najoungkim** [comment]
When the preprocessing scripts get added to the branch, which is contingent on the release of the datasets. @azpoliak might have a clearer idea of when the datasets will be ready for release.

________________________________

**Comment by azpoliak** [comment]
I’m aiming for by next Friday (July 26) the latest. Possibly the day before

**Comment by najoungkim** [comment]
The datasets can now be accessed here: https://github.com/decompositional-semantics-initiative/DNC/
