### ISSUE TITLE
Set up CI testing for outside PRs

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#664]
PRs that aren't coming from the nyu-mll fork of the repo don't trigger CI tests until after they're merged. 

Example: https://github.com/nyu-mll/jiant/pull/663

We should either set up CI for these PRs, or if that's not viable, add a note to the readme asking people to move their code to a branch of nyu-mll (rather than a personal fork) before making a PR.

**Comment by sleepinyourhat** [comment]
@zphang Mind taking a look? Not urgent, but you probably know this best.

**Comment by zphang** [comment]
I believe external PRs should have tests running on them, e.g. https://github.com/nyu-mll/jiant/pull/561

My specific setup might be a little weird because I also have CI tests running for my fork. You should see a check mark on my PR now: https://github.com/nyu-mll/jiant/pull/665

**Comment by sleepinyourhat** [comment]
Looks good!
