### ISSUE TITLE
Can't load for eval / reload when doing finetune only. 

### ISSUE THREAD

**Issue by Iwontbecreative** [nyu-mll/jiant#688]
If I train a model without doing the pretraining phase (e.g by loading it from another checkpoint), it will fail at evaluation because it cannot find a checkpoint.

The checkpoints when finetuning as `model_state_{task}_best.th` but `get_best_checkpoint_path` does not search for this, causing the script to fail.

Fix is to add another format for `get_best_checkpoint_path` or to standardize the model name when saving it in finetuning so it matches normal model names.

**Comment by pruksmhc** [comment]
So just to make sure I understand completely, the problem is when you're only using the finetning phase correct?

**Comment by Iwontbecreative** [comment]
See here: https://github.com/nyu-mll/jiant/blob/9f54df239b21aacbc9ff31a20739fabdf99d88b2/main.py#L497

If you run this part of the code it will fail when trying to eval the best model because it's saved in a different format.

**Comment by sleepinyourhat** [comment]
Do either of you know if this is still open after the recent checkpointing refactor?

**Comment by pruksmhc** [comment]
It shouldn't be.
