### ISSUE TITLE
Revisit the use of Tensorboard

### ISSUE THREAD

**Issue by pruksmhc** [nyu-mll/jiant#694]
Make sure that it's useable/not buggy.

**Comment by sleepinyourhat** [comment]
Still on it? This is the last day I can do much reviewing before Mon.

**Comment by pruksmhc** [comment]
Tensorboard isn't working - there's definitely something wrong with the output of the tensorboard logs. Investigating further now.

**Comment by sleepinyourhat** [comment]
What's the status here?

**Comment by pruksmhc** [comment]
Added a new issue addressing macro/micro.
