### ISSUE TITLE
Conda warning about pip

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#699]
`Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.`

**Comment by prabhakar267** [comment]
I think this is fixed in #826

**Comment by sleepinyourhat** [comment]
Thanks! Closing.
