### ISSUE TITLE
`pyhocon` missing from environment file.

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#701]

**Comment by pruksmhc** [comment]
Addressing here https://github.com/nyu-mll/jiant/pull/702

**Comment by sleepinyourhat** [comment]
@TalLinzen - Update: It looks like this fix came after the latest release version. We'll be pushing a new release soon, but until then, mind trying to work at head (`git checkout master`; `git pull`) and letting us know what issues you hit?
