### ISSUE TITLE
Possible issue: Not loading layer norm parameters

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#714]
I'm seeing these errors when loading a model_state_pretrain checkpoint. These errors only show up for the second target task, probably because the first target task uses the base model parameters, rather than this specialized checkpoint.

06/20 09:59:27 PM: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
06/20 09:59:27 PM: Parameter missing from checkpoint: sent_encoder._text_field_embedder.model.embeddings.LayerNorm.gamma
06/20 09:59:27 PM: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
06/20 09:59:27 PM: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
06/20 09:59:27 PM: Parameter missing from checkpoint: sent_encoder._text_field_embedder.model.embeddings.LayerNorm.beta
06/20 09:59:27 PM: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
06/20 09:59:27 PM: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
06/20 09:59:27 PM: Parameter missing from checkpoint: sent_encoder._text_field_embedder.model.encoder.layer.0.attention.output.LayerNorm.gamma
06/20 09:59:27 PM: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
06/20 09:59:27 PM: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
06/20 09:59:27 PM: Parameter missing from checkpoint: sent_encoder._text_field_embedder.model.encoder.layer.0.attention.output.LayerNorm.beta
06/20 09:59:27 PM: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
06/20 09:59:27 PM: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
06/20 09:59:27 PM: Parameter missing from checkpoint: sent_encoder._text_field_embedder.model.encoder.layer.0.output.LayerNorm.gamma
06/20 09:59:27 PM: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
06/20 09:59:27 PM: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
06/20 09:59:27 PM: Parameter missing from checkpoint: sent_encoder._text_field_embedder.model.encoder.layer.0.output.LayerNorm.beta
06/20 09:59:27 PM: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
06/20 09:59:27 PM: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
06/20 09:59:27 PM: Parameter missing from checkpoint: sent_encoder._text_field_embedder.model.encoder.layer.1.attention.output.LayerNorm.gamma
06/20 09:59:27 PM: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
06/20 09:59:27 PM: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
06/20 09:59:27 PM: Parameter missing from checkpoint: sent_encoder._text_field_embedder.model.encoder.layer.1.attention.output.LayerNorm.beta
06/20 09:59:27 PM: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
06/20 09:59:27 PM: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
06/20 09:59:27 PM: Parameter missing from checkpoint: sent_encoder._text_field_embedder.model.encoder.layer.1.output.LayerNorm.gamma
06/20 09:59:27 PM: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

...

06/20 09:59:27 PM: Loaded model state from [...]/model_state_pretrain_epoch_[...].best_macro.th

**Comment by HaokunLiu** [comment]
pytorch uses different names for parameters of  layernorm in 1.0.0 and 1.0.2 , update pytorch should fix this.

**Comment by sleepinyourhat** [comment]
Thanks!
