### ISSUE TITLE
Broken support for multiple target tasks with fine-tuning and no pretraining

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#723]
If you want to evaluate BERT on a set of target tasks (no extra pretraining, paradigm = finetune), the pre_target_train doesn't kick in, and the model crashes when it tries to restore after finishing a target task.

**Comment by pruksmhc** [comment]
Probably what should be done is that we save the pretrained BERT model state (the one from huffingface) should be what pre_target_train gets in this case -  thoughts?

**Comment by sleepinyourhat** [comment]
It looks like we do—I think the error is in loading it. Working on a fix.
