### ISSUE TITLE
tutorial.conf missing

### ISSUE THREAD

**Issue by pruksmhc** [nyu-mll/jiant#725]
pyhocon doesn't get automatically installed (needs to be added to conda env)

the  line "python -m nltk.downloader -d  perluniprops nonbreaking_prefixes punkt" mentioned in the tutorial didn't download nonbreaking_prefixes

config/tutorial.conf -> change to config/demo.conf

**Comment by sleepinyourhat** [comment]
Forked the first two off to request more information. #744 #702.

**Comment by sleepinyourhat** [comment]
Rereading the tutorial, the instructions ask you to _create_ tutorial.conf. I'll make that more explicit and close this out.
