### ISSUE TITLE
Running the baselines

### ISSUE THREAD

**Issue by Narsil** [nyu-mll/jiant#743]
I'm mainly interested in this repo in order to reproduce easily  some baselines on GLUE/SuperGLUE.

Are there already existing configurations to reproduce some results from established papers ? 
Like BERT/XLNet/XLM on GLUE/superGLUE tasks ?

It would be even better if we had both training phase + evaluation (to compare efficiency metrics like clock time) and from_pretrained results (to check easily how the metrics are evaluated, and what preprocessing was used for each method. 

I checked the pre-existing configurations like `config/superglue-bert.conf` which looking at the comment in the file should do one of the above. Yet the file does not pass (`AssertionError: If you're pretraining on a task you plan to reuse as a target task, set
allow_reuse_of_pretraining_parameters = 1 (risky), or train in two steps:
train with do_pretrain = 1, do_target_task_training = 0, stop, and restart with
do_pretrain = 0 and do_target_task_training = 1.
`)

If the configuration files do exist, maybe we could add some docs on how to run them ?

**Comment by pruksmhc** [comment]
There are example configuration files under the [config](https://github.com/nyu-mll/jiant/tree/master/config) directory, and you can find tutorials on how to run them [here](https://github.com/nyu-mll/jiant/blob/master/tutorials/setup_tutorial.md).

**Comment by sleepinyourhat** [comment]
No—we don't have the exact preprocessing/training code to reproduce those papers exactly. We can come very close to the BERT results with existing scripts, but it's possible that they may not be in great shape at head—issues/comments/patches welcome!

We're planning to add XLNet and XLM reasonably quickly once they're added to the Huggingface repo.

For the issue you're hitting, my guess is that you're not setting any target tasks, and you're inheriting something incoherent from defaults. The script Yada linked to will hopefully get around that.
