### ISSUE TITLE
Merge bert_model, use_elmo, openai_transformer, and word_embs flags

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#767]
This should simplify some documentation quite a bit by making it clearer that we treat all of these as the same glass of objects. The result would probably be a single flag called something like 'input_module' that can take values like 'bert-base-cased', 'gpt', and 'glove'.

**Comment by pruksmhc** [comment]
Probably should be called word_embs since that's what we're treating them as in jiant.

**Comment by sleepinyourhat** [comment]
Could be confusing, too, since that'd probably imply something simple and fixed. I'm not sure the 'contextualized word embedding idea' term on, and even then I'm not sure it applies to BERT.
