### ISSUE TITLE
Update and Extend the inference script

### ISSUE THREAD

**Issue by zphang** [nyu-mll/jiant#770]
The inference script [`cola_inference.py`](https://github.com/nyu-mll/jiant/blob/master/cola_inference.py) currently only supports inference for CoLA. We should consider extending the script to support a greater number of tasks. One of the main obstacles to this is that the task class definitions currently do not have enough structure to neatly support this functionality. To extend the inference script to other tasks, we will need to make broad (but not necessarily significant) changes to many task definitions.

I propose the following:

- Separate corpus-level inference (compute and save predictions and output evaluation metrics) and REPL functionality into different scripts. Both scripts require standardization of different functionality from the tasks, and it would be easier to consider them separately.
- In both cases, support only a subset of tasks, and explicitly document and check for this in the respective scripts. We can start with just supporting the GLUE and SuperGLUE tasks, and we can extend this over time. 

In terms of proposed modifications to tasks:
- Supporting corpus-level inference should be straightforward. It should only entail defining separate methods for loading train/val/test data, and potentially additional wrapping for the outputs/metric computation. I believe this can be implemented neatly.
- Supporting REPL capability more generally will be a little more involved. We will need to standardize an API for mapping potentially multiple inputs into task-specific logic for creating a full example instance, or other UI considerations (e.g. inputs that contain spans).

**Comment by sleepinyourhat** [comment]
This all sounds reasonable and quite useful! Any interest in taking the lead?

Probably won't make it into 1.0, but good target for the next release?

**Comment by zphang** [comment]
Yep, will take the lead on this. I created the issue to seek feedback on the proposal, so I will go ahead and start work on this.

**Comment by sleepinyourhat** [comment]
Great! @pruksmhc @W4ngatang, any comments?

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/770.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
