### ISSUE TITLE
Clarify the WSC–Edge Probing distinction

### ISSUE THREAD

**Issue by sleepinyourhat** [nyu-mll/jiant#775]
As in #773, issues with WSC trigger errors that refer to Edge Probing. We should make it clear which parts of the code are specific to edge probing (i.e., training light models without the possibility of backprop), and which parts just apply to edge classifiers of any kind. This should mostly be a variable name/comment fix.

**Comment by sleepinyourhat** [comment]
Yada knows the WSC angle on this, though @iftenney likely wrote much of the relevant code.

**Comment by pruksmhc** [comment]
I had adapted part of Ian's code for span classification - I'll clean up the references!
