### ISSUE TITLE
Support debugging mode 

### ISSUE THREAD

**Issue by pruksmhc** [nyu-mll/jiant#779]
Contemplating if it would be helpful to create a debug mode that would print out intermediate states, labels, etc at validation time. It wouldn't be too much added code, and would make debugging much easier.

**Comment by pyeres** [comment]
Recommending that we leave this functionality to the [pdb module](https://docs.python.org/3/library/pdb.html) (which is pretty great).

**Comment by pyeres** [comment]
Closing — please reopen if further discussion would be helpful.
