### ISSUE TITLE
Using STILTS style setup with diagnostics will not use the correct classifier

### ISSUE THREAD

**Issue by W4ngatang** [nyu-mll/jiant#829]
If I run MNLI pretraining, then RTE target training with the diagnostics as additional target tasks that use the RTE classifier, `main.py` will load the checkpoint from pretraining, which is an untrained RTE model, and we'll get terrible performance on the diagnostics.

The issue is that on [this line](https://github.com/nyu-mll/jiant/blob/master/main.py#L266), we're not checking to see if the task uses another task's classifier, so we don't find any target train checkpoints and we load the pretraining checkpoint instead.

**Comment by sleepinyourhat** [comment]
Safe to close?

**Comment by W4ngatang** [comment]
closed I think with #830
