### ISSUE TITLE
boolq task data preprocessing

### ISSUE THREAD

**Issue by desperadoola** [nyu-mll/jiant#836]
https://github.com/nyu-mll/jiant/blob/c713766fdbbb1dd50b4fc4afd558eaf9d5c6f948/jiant/tasks/tasks.py#L2821

Correct me if I'm wrong. Here we concatenate the sequence as [CLS] + context + [CLS] question + [SEP], instead of [CLS] + context + [SEP] question + [SEP], any reason doing that?

**Comment by sleepinyourhat** [comment]
That does sound fishy, though I don't know this part of the code well. @W4ngatang, mind taking a look?

**Comment by W4ngatang** [comment]
Oh yeah, that's a brainfart. I'll push a fix, though I expect numbers won't change that much (we were already in-line with the BERT baseline in the original work). Thanks for the catch !
