### ISSUE TITLE
Automate hyperparameter tuning

### ISSUE THREAD

**Issue by pruksmhc** [nyu-mll/jiant#872]
Right now, the way to do this is to have multiple experiments running with different hyperparameter states. 
We could incorporate https://github.com/Open-ASAPP/flambe or try to interface with some of what they're working on, or build our own.

**Comment by sleepinyourhat** [comment]
I think the only simple/easy setup is the one we already have—generating shell commands. For anything more complex, I think getting it right would be pretty subtle, so I'd vote for Flambé or something similar.

**Comment by pyeres** [comment]
Closing as duplicate of more recent issue (#964).
