### ISSUE TITLE
BERT Tokenization for WiC

### ISSUE THREAD

**Issue by kanishkamisra** [nyu-mll/jiant#888]
Hi, 

I am trying to replicate the SuperGLUE version of the WiC classification model (using BERT) and I cant quite wrap my head around the code. So, as I understand, the way it's done is we have the following, with "b" and "d" being the marked words:

* **sentence1:** ["a", "b", "c"]
* **sentence2:** ["d", "e"]
* **idxs1:** (1,2)
* **idxs2:** (0,1)

using the preprocessing code defined [here](https://github.com/nyu-mll/jiant/blob/b9bffb99d80c7f5714c4f26ec5ffdef09dce76f1/jiant/tasks/tasks.py#L2453), it's going to concatenate the two inputs and add the BERT boundary tokens (CLS and SEP), making it:

* **input:** ["[CLS]", "a", "b", "c", "[SEP]", "d", "e", "[SEP]"]
* **idxs1:** (2, 3)
* **idxs2:** (5, 6)

Now this is passed to the indexer which seems to just map the tokens to BERT's vocab (btw I am not sure what `bert-xe-cased` is, but assuming the vocab is the same as the BERT models available for download), what happens when one of the tokens is out of vocab. From the other scripts I see you are using the MosesTokenizer for wic inputs, especially to get the `(start, end)` values. Does the indexer assign an '[UNK]' to it (and its corresponding input id). If it doesn't and uses its full word-piece capabilities, then wont this mess up the marked word indices?

Please let me know if I have been wrong in my assumptions about the code, I am new to the config based libraries such as allen-nlp and jiant but I love the idea and am trying to get used to them. Thanks for making it possible and I hope you can help me out.

**Comment by sleepinyourhat** [comment]
@pruksmhc @W4ngatang

**Comment by pruksmhc** [comment]
Hi Kanish, we first preprocess the two spans to whatever tokenization is associated with the BERT model you're using. If a sub-word does not appear in BERT, then it will be assigned BERT's unknown token (in fact, that is a requirement, see here https://github.com/nyu-mll/jiant/blob/a1e9abf03fc8edf9a6b192cf7cb84d2ccfa1ef4c/jiant/pytorch_transformers_interface/modules.py#L202 ). @W4ngatang was in charge of the WiC model, so definitely jump in here.

**Comment by kanishkamisra** [comment]
Hey! Thanks for responding, so if both marked words are oov for bert (which is the case in many instances in WiC) are they just processed as unk?

**Comment by pruksmhc** [comment]
Hi Kanish, I think what you're seeing in MosesTokenizer is in our tests file. If you're running BERT, the tokenization should be set to whatever BERT model you have. However, yes, they will be processed as UNK if marked words are OOV.

**Comment by kanishkamisra** [comment]
Oh I see, thanks. What happens when marked words aren't oov but are processed as wordpieces? I couldn't make out from the code how you process them. so if the word is abc and its word pieces are a, b, c; how do you obtain the vector representing the word?

**Comment by W4ngatang** [comment]
Hey Kanishka,

We add the vectors corresponding to the word pieces, then concatenate that
representation to the overall sentence (pair) representation. I think this
all happens in `jiant/modules/classifier.py`.

**Comment by kanishkamisra** [comment]
Ah I see! Thank you for helping out!
