### ISSUE TITLE
ValueError on aligner_fun for RoBERTa tokenizer

### ISSUE THREAD

**Issue by zphang** [nyu-mll/jiant#934]
```python
from jiant.utils.retokenize import get_aligner_fn
aligner_fn = get_aligner_fn("roberta-large")
aligner, processed_sentence_tokens = aligner_fn('ξ word')
aligner.project_span(0, 1)
```

Leads to `ValueError: min() arg is an empty sequence`.

No error if we replace the input text with `'a word'`.

**Comment by zphang** [comment]
Follow-up: Another RoBERTa alignment bug, not related to odd characters (but still pertaining to first tokens?)

We're going to match each space-tokenized length-1 span to the corresponding the corresponding token spans.

Setup code:
```python
from jiant.utils.retokenize import get_aligner_fn
roberta_aligner_fn = get_aligner_fn("roberta-large")
bert_aligner_fn = get_aligner_fn("bert-large-cased")
bad_text = 'Larger than life.'
good_text = 'This was larger than life.'

def print_alignment(aligner_fn, input_text):
    aligner, processed_sentence_tokens = aligner_fn(input_text)
    for i, token in enumerate(input_text.split()):
        print(token, processed_sentence_tokens[slice(*aligner.project_span(i, i+1))])
```

RoBERTa will never catch the starting "L":

```
>>> print_alignment(roberta_aligner_fn, bad_text)
Larger ['arger']
than ['Ġthan']
life. ['Ġlife', '.']
```

Compare to these other good examples:

```
>>> print_alignment(roberta_aligner_fn, good_text)
This ['ĠThis']
was ['Ġwas']
larger ['Ġlarger']
than ['Ġthan']
life. ['Ġlife', '.']
```

```
>>> print_alignment(bert_aligner_fn, good_text)
This ['This']
was ['was']
larger ['larger']
than ['than']
life. ['life', '.']
```

```
>>> print_alignment(bert_aligner_fn, bad_text)
Larger ['Large', '##r']
than ['than']
life. ['life', '.']
```

@phu-pmh @pruksmhc

**Comment by pruksmhc** [comment]
@iftenney

**Comment by iftenney** [comment]
I wasn't involved with implementing RoBERTa tokenization, but maybe @sleepinyourhat or @HaokunLiu knows more?

**Comment by iftenney** [comment]
#903 #890

**Comment by iftenney** [comment]
The most stable way to fix this is probably to do away with the character-alignment retokenization scheme, and just do something like this: https://github.com/google-research/bert#tokenization:

> If you have a pre-tokenized representation with word-level annotations, you can simply tokenize each input word independently, and deterministically maintain an original-to-tokenized alignment:
```
### Input
orig_tokens = ["John", "Johanson", "'s",  "house"]
labels      = ["NNP",  "NNP",      "POS", "NN"]

### Output
bert_tokens = []

# Token map will be an int -> int mapping between the `orig_tokens` index and
# the `bert_tokens` index.
orig_to_tok_map = []

tokenizer = tokenization.FullTokenizer(
    vocab_file=vocab_file, do_lower_case=True)

bert_tokens.append("[CLS]")
for orig_token in orig_tokens:
  orig_to_tok_map.append(len(bert_tokens))
  bert_tokens.extend(tokenizer.tokenize(orig_token))
bert_tokens.append("[SEP]")

# bert_tokens == ["[CLS]", "john", "johan", "##son", "'", "s", "house", "[SEP]"]
# orig_to_tok_map == [1, 2, 4, 6]
```

**Comment by HaokunLiu** [comment]
Yes, Ian proposed this alternative last time, I didn’t want to make that
level of refactoring then. But since our current aligner is going wrong in
some cases. It’s better to switch align method sooner than later.

We can discuss more tomorrow at the meeting.

**Comment by pruksmhc** [comment]
Actually, I wrote a similar "per-token" function for BERT - would be pretty easy to get it to work for RoBERTa as well

**Comment by pruksmhc** [comment]
Looks like spacy also has something for token alignment https://pypi.org/project/spacy-pytorch-transformers/
