### ISSUE TITLE
Potential issue with metrics calculation when using multi-GPU training

### ISSUE THREAD

**Issue by zphang** [nyu-mll/jiant#947]
When using multi-GPU training, occasionally I encounter in accurate computation of metrics. For example, training RTE on RoBERTa-large, which should get close to 100% training accuracy after a few epochs, it is possible to see >100% training accuracy.

`11/02 09:02:46 PM: Update 3171: task rte, batch 46 (3171): accuracy: 1.0167, rte_loss: 0.0107`

I suspect the cause of this is that to support multi-GPU, we're calling `DataParallel`, which should be well-behaved for computing the model in parallel across multiple GPUs, but may cause issues because we are also computing/accumulating metrics in our forward step, which may not be multi-processing safe.

**Comment by sleepinyourhat** [comment]
@pruksmhc - Would you mind taking a look at this ASAP or else removing multi-GPU support for now. We're blocked on releases until we're sure multi-GPU is bulletproof.

**Comment by sleepinyourhat** [comment]
If this is really just a small error in validation metric calculation, then it's not a big deal. But this looks like the kind of thing that could very easily be a sign of a deeper problem.

**Comment by pruksmhc** [comment]
I just verified that it indeed is a multi-GPU problem, and that some of the variables in the metrics are being updated at different times (which means depending on which GPU get_metrics() is called on, accuracy can be more than 1.0. 
I'm working on a fix, which will basically be calling task.update_metrics() in _forward as opposed to the various forward functions in jiant/models.py. 
For future reference, for multi-GPU case, any function or operation executed in the scope of the model (self._model) is going to be executed with multi parallelism. However, anything outside that scope (for example trainer scope) is executed on one GPU.
