### ISSUE TITLE
Significantly improved WiC results in v1.2.1 ?

### ISSUE THREAD

**Issue by danlou** [nyu-mll/jiant#957]
Hi,

I've just tried to replicate the WiC baseline using:

`./scripts/superglue-baselines.sh wic`

And got the following results:

`wic     micro_avg: 0.735, macro_avg: 0.735, wic_accuracy: 0.735, wic_f1: 0.759, wic_precision: 0.696, wic_recall: 0.834`

This accuracy of 0.735, using bert-large-cased, is much higher than the 0.696 reported in the SuperGLUE leaderboard.

It seems that you've recently fixed an issue related to indexing the target words (https://github.com/nyu-mll/jiant/pull/916). Do you think this fix could the difference, or maybe there's something else I'm missing?

Thanks!

**Comment by HaokunLiu** [comment]
The result here is just on validation set, to get the test result, you will
need to find the prediction file and upload it to the leaderboard.

We don’t have anything fancy in our model, I won’t expect the test result
to be any better than what’s in the leaderboard.

**Comment by danlou** [comment]
Yup, that explains it, sorry I missed that.

I'll upload it to wic's codalab leaderboard (pending approval) and will post the results here to clarify the impact of this change on wic's performance.

**Comment by HaokunLiu** [comment]
That will be nice, thank you.

**Comment by danlou** [comment]
I'm having some trouble replicating the score. I converted the results generated to WiC.jsonl to the codalab's format (single T/F per line, ordered by 'idx') and I'm getting a score of 47.8571428571.

Going by the timestamps in jiant's log, WiC.jsonl includes the predictions for the test set. Also, the number of entries also match the test set (1400).

I'm attaching the log and predictions, in case it helps.
[log.log](https://github.com/nyu-mll/jiant/files/3830826/log.log)
[WiC.jsonl.zip](https://github.com/nyu-mll/jiant/files/3830829/WiC.jsonl.zip)
[output.zip](https://github.com/nyu-mll/jiant/files/3830830/output.zip)

**Comment by HaokunLiu** [comment]
Thank you, I may have time to check this out next week.

**Comment by danlou** [comment]
Thanks. If in the meantime you want me to test something, please don't hesitate to ask.

**Comment by zphang** [comment]
*This is an automatically generated comment.*

As we update `jiant` to v2.x, `jiant` v1.x has been migrated to https://github.com/nyu-mll/jiant-v1-legacy. As such, we are closing all issues relating to `jiant` v1.x in this repository.

If this issue is still affecting you in `jiant` v1.x, please follow up at https://github.com/nyu-mll/jiant-v1-legacy/issues/957.

If this issue is still affecting you in `jiant` v2.x, reopen this issue or create a new one.
