### ISSUE TITLE
Update Transformers to v2.2.0, ALBERT Support

### ISSUE THREAD

**Issue by zphang** [nyu-mll/jiant#972]
https://github.com/huggingface/transformers/releases/tag/v2.2.0

**Comment by sleepinyourhat** [comment]
Looking at the GLUE leaderboard lately, I'm optimistic that the era of 100m-to-1b parameter transformers isn't over yet. 

In terms of our priorities:
- I think it makes sense to try to track the latest NLU model launches from `transformers` as closely as we can (in this case, that means setting up ALBERT support as soon as anyone has a spare afternoon, and possibly other similar models like DistilRoBERTa, to the extent that's easy).
- I think we can get away without T5 support, at least in the near future. Converting our full set of tasks to their sequence-to-sequence format would be a substantial undertaking, and it seems likely that most near-future strong models in this area will stick with the BERT-style encoder formulation that we already support.
- However, it seems likely that models like these will continue to grow, and that we'll continue to want to use the largest available models in some cases. This means that extensive/seamless multi-GPU support needs to stay fairly prominent on our near-future roadmap.
