### ISSUE TITLE
sts-b task score is far worse than other GLUE tasks

### ISSUE THREAD

**Issue by zxznm** [nyu-mll/jiant#975]
Hello,
I'm evaluating my GPT style model pretrained on TEXT8 dataset with GLUE.
Below is the evaluation result.

```
CoLA | SST-2 |     MRPC    |    QQP    |    STS-B    | MNLI | QNLI | RTE  | WNLI
19.1 |   85  | 82.5 / 71.6 | 78.4 / 82 | 41.6 / 39.4 | 62.8 | 74.6 | 57.4 | 56.3
```

Compare to other GLUE tasks, STS-B scores seem far worse than baseline in leader board.
Does anyone know why model works bad on STS? Thanks a lot.

**Comment by HaokunLiu** [comment]
How did you add your own GPT style model to jiant?
You might want to check if uses_mirrored_pair has been set up correctly. For GPT-like model, this should be True.

**Comment by zxznm** [comment]
Thank you for your reply. 
I've pretrained my model using pytorch-transformer library, so load it to jiant like other pretrained transformer models.
I checked `uses_mirrored_pair = True`.

**Comment by HaokunLiu** [comment]
Oh, everything seems reasonable, except the result.
Could you post your log file here?
